### ISSUE TITLE
Support for a more recent Java version

### ISSUE THREAD

**Issue by aljoshakoecher** [RMLio/rmlmapper-java#101]
Hi there,

do you plan on supporting a more recent Java version? I came across a problem which seems to be caused by the rmlmapper jar embedding some of its dependencies. This leads to a problem with conflicting dependencies on JDK version > 9, please see [this StackOverflow post](https://stackoverflow.com/questions/66319001/excluding-dependency-does-not-help-to-fix-the-package-org-w3c-dom-is-accessible) for a full description of the issue.

I had a look into `src/main/resources`, found GrelFunctions.jar and this related issue: #26. Files within the resources folder get embedded into the jar, so could this be the reason why rmlmapper embeds some unwanted dependecies? 
Additionally, PR #84 seems to bring a solution for unwanted embedding of dependencies. Do you plan on merging this for the next version?

**Comment by DylanVanAssche** [comment]
Hi @aljoshakoecher !

Thanks for using RML!
We recently merged PR #84 and released it in [v4.9.3](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.9.3).
Does that solve your issue already? If not, could you please clarify which dependencies are causing problems for you?
