### ISSUE TITLE
Is the "rmlio" organization on Docker Hub the same as this one?

### ISSUE THREAD

**Issue by alexkreidler** [RMLio/rmlmapper-java#109]
The [rmlio](https://hub.docker.com/u/rmlio) organization on Docker Hub has published some docker images. However, reading the README I don't see a reference to it. 

Are those images built by you all? 

It would be great to add a note to the README if so, and maybe also think about building the Docker images in a CI pipeline.

Thanks!

**Comment by pheyvaer** [comment]
Hi @alexkreidler, 

Yes these images are build by us! The images are automatically build every time we push to master (or add a tag). The building happens by Docker Hub itself, which is monitoring this repo.

**Comment by DylanVanAssche** [comment]
We will add a reference in the README in the next release.

**Comment by alexkreidler** [comment]
Great thanks! I'll leave this open so you can keep track of it.

**Comment by pheyvaer** [comment]
@alexkreidler We added more info in our README https://github.com/RMLio/rmlmapper-java#dockerhub
