### ISSUE TITLE
Primary interlinking and java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by cordawyn** [RMLio/rmlmapper-java#11]
Hi!

I have a simple table "surveys" (containing some survey data, in a postgresql DB) with the following columns (simplified for this report):
* id - id of the survey (int)
* name - name of the person taking the survey (string)
* product - name of the product used by the person (string)

I would like to create a couple of resources while mapping it to RDF: "Person" and "Product". Additionally, I would like to add statements like "person -- usesProduct -- product".

So I'm using the following mapping:

```TURTLE
<#int_test> a d2rq:Database .

<#PersonTriples> a rr:TriplesMap ;

  rml:logicalSource [
    rml:source <#int_test> ;
    rr:sqlVersion rr:SQL2008 ;
    rr:tableName "surveys" ] ;

  rr:subjectMap [
    rr:termType rr:BlankNode ;
    rr:class ex:Person ] ;

  rr:predicateObjectMap [
    rr:predicate foaf:name ;
    rr:objectMap [
      rr:template "{name}" ;
      rr:termType rr:Literal ] ] ;

  rr:predicateObjectMap [
    rr:predicate ex:usesProduct ;
    rr:objectMap [
      rr:parentTriplesMap <#ProductTriples> ] ] .

<#ProductTriples> a rr:TriplesMap ;

  rml:logicalSource [
    rml:source <#int_test> ;
    rr:sqlVersion rr:SQL2008 ;
    rr:tableName "surveys" ] ;

  rr:subjectMap [
    rr:termType rr:BlankNode ;
    rr:class ex:Product ] ;

  rr:predicateObjectMap [
    rr:predicate ex:productName ;
    rr:objectMap [
      rr:template "{product}" ;
      rr:termType rr:Literal ] ] .
```

There are no data sources (columns) to produce conventional URIs neither for `ex:Person`, nor for `ex:Product` resources, as you can see. So I'm using blank nodes for them.

When I'm running the mapping:

```
$ java -jar rmlmapper-4.0.0-r48-jar-with-dependencies.jar -m mapping.rml.ttl
```

it runs for some time (w/o output) and then dies with:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at be.ugent.rml.Utils.toNQuads(Utils.java:339)
	at be.ugent.rml.cli.Main.writeOutput(Main.java:203)
	at be.ugent.rml.cli.Main.main(Main.java:138)
```

If I comment out `rr:predicateObjectMap` statement with `rr:parentTriplesMap` above, there's no problems and I get the RDF output (but naturally, without "usesProduct" statements).

Could it be because I'm using blank nodes?

If so, how would you produce "normal" URIs for these resources? I could use a template with some UUID generator, perhaps. But I could not figure out how to do that.

(This report applies to the rmlmapper 9a64f3e (latest commit), but was reproducible in earlier versions too).

**Comment by pheyvaer** [comment]
Hi,

The `java.lang.OutOfMemoryError` has probably to do with the fact that all the data together with the generated triples does not fit in memory. The effect of blank nodes vs IRIs is not clear here, i.e., you could use IRIs that result in a bigger in memory storage. Could you try again while giving more memory to the Java VM?

**Comment by cordawyn** [comment]
The table is not so large, it's about 4k records.

Anyway, I tried running it with:
```
$ java -Xms4096m -Xmx4096m -jar rmlmapper-4.0.0-r48-jar-with-dependencies.jar -m mapping.rml.ttl
```
...but with the same outcome.
Sorry, that's as much RAM as I could allocate (there's only 4GB available on my PC).

And here I was hoping to handle millions of records with rmlmapper... 😄
(I'll try to debug it somehow, but I'm not really a Java dev).

**Comment by pheyvaer** [comment]
If you have a dump of the records in CSV, we might have a look at what is going wrong.

**Comment by cordawyn** [comment]
The original table contains some "sensitive" data, so I tried to minimize and anonymize it. And I think I managed to pin down the source of evil. Given the above mapping adapted to CSV input:
```
...
  rml:source "surveys.csv" ;
  rml:referenceFormulation ql:CSV .
...
```
and the following simple input (just 2 records):
```CSV
name,email,product
John Doe,john.doe@example.com,Classic
Jane Doe,jane.doe@example.com,Deluxe
```
`rmlmapper` produces:
```
_:0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.                                                                                                                                  
_:0 <http://xmlns.com/foaf/0.1/name> "John Doe".
_:0 <http://xmlns.com/foaf/0.1/email> "john.doe@example.com".
_:0 <http://example.com/usesProduct> _:1.
_:0 <http://example.com/usesProduct> _:2.
_:3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
_:3 <http://xmlns.com/foaf/0.1/name> "Jane Doe".
_:3 <http://xmlns.com/foaf/0.1/email> "jane.doe@example.com".
_:3 <http://example.com/usesProduct> _:1.
_:3 <http://example.com/usesProduct> _:2.
_:1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Product>.
_:1 <http://example.com/productName> "Classic".
_:2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Product>.
_:2 <http://example.com/productName> "Deluxe".
```
So "all users are using all products" – "ex:usesProduct" is eventually multiplied by the number of records in the source data (but it should be just 1-to-1 correspondence in my case). If there's 4k records, every user ends up using all 4k products (that's 4k users X 4k products).

**Comment by pheyvaer** [comment]
Yes, that is the expected behaviour. If you want a 1-on-1 mapping you need to add a Join Condition to 
```
rr:predicateObjectMap [
    rr:predicate ex:usesProduct ;
    rr:objectMap [
      rr:parentTriplesMap <#ProductTriples> ]
```
For your example, this can be
```
rr:predicateObjectMap [
    rr:predicate ex:usesProduct ;
    rr:objectMap [
      rr:parentTriplesMap <#ProductTriples>;
      rr:joinCondition [
        rr:child "name";
        rr:parent "name"
      ]
    ]
```

**Comment by cordawyn** [comment]
It almost worked 😄

I think that your suggestion relies on "name" being unique, which is not true in my case. I could use "email" for that, but with so much rubbish in the data sources I have to process, there's no guarantee that it uniquely identifies a person (e.g. there's many blank name/email entries) – hence I'm assuming the worst and leave it up to some post-processing to figure out if some resources refer to the same entity.

... Unless I can somehow instruct rmlmapper to treat every person/product as unique per DB record?

**Comment by cordawyn** [comment]
I've used "id" column for joining instead of "name" or "email" – this sort of solved my problem, but that'll work until I encounter an "id-less" table 😄.

Anyway, thank you very much for help, @pheyvaer ! You can close this issue, I guess, unless you have something to add.

**Comment by pheyvaer** [comment]
Nice that you got it working :smile: In all cases we have encountered so far there is always at least one column that is unique or at least a combination of columns is unique.
