### ISSUE TITLE
controls_if example available?

### ISSUE THREAD

**Issue by paulakeen** [RMLio/rmlmapper-java#114]
I'm struggling with the implementation of an if decision with RML without having to pre-manipulate the source. I see that RML has a pre-define _controls_if_  function, but cannot figure out how it does work, and could not find any example in the Issues nor in google...

Tks.

**Comment by bjdmeest** [comment]
The controls_if function is tested using test cases RMLFNOTCAB0003-RMLFNOTCAB0006 at https://github.com/RMLio/rml-fno-test-cases, would this help?
