### ISSUE TITLE
Is it possible to use prefixes with templates?

### ISSUE THREAD

**Issue by paulakeen** [RMLio/rmlmapper-java#115]
When working with turtle serialisations, it would be great if it was possible to replace the URI of the subject template with its prefix. But I couldn't work it around. Is this even possible in RML? 
Tks.

**Comment by bjdmeest** [comment]
Could you provide a minimal example, just to make sure we're on the same page? :)

**Comment by paulakeen** [comment]
For example, we'd like to have an outcome of the type:

````
@prefix foaf: <http://xmlns.com/foaf/0.1/>
@prefix ex: <http://example.org#>

ex:paula a foaf:Person ;
foaf:givenName "Paula"
foaf:familyName "Keen"
````


instead of:

````
@prefix foaf: <http://xmlns.com/foaf/0.1/>
@prefix ex: <http://example.org#>

<http://example.org#paula> a foaf:Person ;
foaf:givenName "Paula"
foaf:familyName "Keen"
````


instead of

**Comment by bjdmeest** [comment]
As far as I know, this is out of scope of [R2]RML. Instead, I created a new issue in the mapping challenges repository of the Knowledge Graph Construction Community Group: https://github.com/kg-construct/mapping-challenges/issues/34
