### ISSUE TITLE
example of output to a SPARQL endpoint

### ISSUE THREAD

**Issue by CyberDaedalus00** [RMLio/rmlmapper-java#117]
I was looking around and couldn't find an example or documentation about how to send the generated triples to a SPARQL endpoint.

Can someone provide some guidance or point me to some documenation?

**Comment by DylanVanAssche** [comment]
Hi @CyberDaedalus00 !

Thank you for your interest in RML!

> I was looking around and couldn't find an example or documentation about how to send the generated triples to a SPARQL endpoint.

This feature was recently added in the v4.10.0 release where Logical Target support was added.

> Can someone provide some guidance or point me to some documenation?

There's no tutorial yet on our website (https://rml.io/docs), but an example is available in the tests:

- **SPARQL endpoint description**: https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/web-of-things/logical-target/sparql/mapping.ttl#L25-L28
- **Logical Target description**: https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/web-of-things/logical-target/sparql/mapping.ttl#L30-L32
- **Logical Target integration with RML Term Maps**: https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/web-of-things/logical-target/sparql/mapping.ttl#L64

We have also released the specifications for Logical Target and its RML integration which contain a lot of examples:
- **DataIO (Target)**: https://rml.io/specs/dataio
- **Target in RML**: https://rml.io/specs/rml-target

You can read more about Logical Target in our paper at ICWE2021:

- **Springer publication**: https://doi.org/10.1007/978-3-030-74296-6_26
- **Preprint & presentation**: https://dylanvanassche.be/publications/#icwe2021
