### ISSUE TITLE
Special characters like ≥ becomes ? in the RDF output

### ISSUE THREAD

**Issue by ammar257ammar** [RMLio/rmlmapper-java#122]
When mapping a CSV file to RDF, I have some values like "≥2" which appears in the output RDF as "?2"

Does rmlmapper handle such characters? and what is the right way to do that?

**Comment by pheyvaer** [comment]
This might be due to the encoding. Can't you try the following?

````
java -Dfile.encoding=UTF-8 -jar rmlmapper.jar
```
