### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by valentinoli** [RMLio/rmlmapper-java#123]
Hello,
I'm trying to build the jar with `mvn install`. The build fails with a test failure:

```
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   Mapper_OracleDB_Test.doMapping:104->mappingTest:121 » SQL No suitable driver f...
[INFO]
[ERROR] Tests run: 518, Failures: 0, Errors: 1, Skipped: 7
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:20 min
[INFO] Finished at: 2021-07-19T11:50:30+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project rmlmapper: There are test failures.
```

I have JDK 16 and maven 3.8.1 installed.

Can someone help me?
Thanks in advance

**Comment by pheyvaer** [comment]
Hi @valentinoli ,

It fails because of the Oracle tests. We can't include the Oracle driver directly, because of the licensing. You can build the jar by skipping the tests `mvn clean install -DskipTests=true` or you can downloaded the latest jar from the releases page.

**Comment by valentinoli** [comment]
Thank you. I didn't realize I could download the jar from releases.
