### ISSUE TITLE
Allow XPath expressions in RML whose result is a string

### ISSUE THREAD

**Issue by IanEmmons** [RMLio/rmlmapper-java#128]
When translating an XML file, rml:reference properties in the RML have values that are XPath expressions.  If such an XPath expression results in a node or a node-set, all is well.  The mapper uses XPath's inherent ability to convert a node-set into a string and then uses that string in the RDF output.  However, if the XPath result is of type string, the mapper fails because it is expecting a node-set.  This is easily reproduced by wrapping an XPath expression in a string function, like so:

```
normalize-space(/my/xpath/expression/that/produces/a/node/set)
```

It would be helpful if the mapper would handle a string result as well as a node-set, because the functions available in XPath are fairly rich and can in many cases sidestep the need for RML function calls.

**Comment by DylanVanAssche** [comment]
I can now reproduce it and have a fix ready.
Will be available in the next release!

Thanks for your report!
