### ISSUE TITLE
 Test case of the  array of array in json

### ISSUE THREAD

**Issue by bilalbenma** [RMLio/rmlmapper-java#130]
I'm trying to map the  JSON file to RDF, The problem that I faced is the following: I can not iterate correctly in order to reach all the attributes inside the **skills array**. I tried all the solutions presented in: [RML Mapper for array of array in json](https://stackoverflow.com/questions/50858420/rml-mapper-for-array-of-array-in-json), but I still faced the same issue. The following code represents a part of the JSON file that I tried to generate from the RDF file. 
**Note1**:  to convert the rml mapping file to RDF I used the [ SDM-RDFizer](https://github.com/SDM-TIB/SDM-RDFizer). 
**Note2**: Can we consider that the  [ SDM-RDFizer](https://github.com/SDM-TIB/SDM-RDFizer) cannot deal with the array of the array test cases. 
**Note3**: I used the following iterator to reach the skills array: `$.characters[*].skills.[*]`
```
{
	"characters": [
		{
			"uid": "kuyD47M35RL3iFv55uJi9i",
			"skill_name": "Software Development",
			"proxy_name": "",
			"syn_names": "",
			"has_direct_child_skills": 1,
			"has_indirect_child_skills": 1,
			"has_parent_skills": 0,
			"has_siblings_skills": 0,
			"has_relatives_skills_categories": 0,
			"rating_type": 1,
			"rating_legend": 25,
			"parent_name": "",
			"description": "",
			"skills": [
			  {
			    "uid": "2mJSma8Qzm5p7hHRKJfk3Q",
                            "skill_id": "4gzJv6MYGhidvV4WRnY6EV"
			  }
			  ]
			
		}
	]
}
```

**Comment by thomas-delva** [comment]
Hi, with the RMLMapper, using the iterator `$.characters[*].skills.[*]` allows me to generate RDF as expected.

I used this mapping: [mapping.rml.ttl](https://github.com/RMLio/rmlmapper-java/files/7234059/mapping.rml.ttl.txt)
And got the following triple as output:
```ttl
<http://example.com/4gzJv6MYGhidvV4WRnY6EV> <http://example.com/uid> "2mJSma8Qzm5p7hHRKJfk3Q".
```

Does this answer your question? If you have an example of the output you want I could offer more complete help.
