### ISSUE TITLE
Compile/install error related to tools.jar on Win

### ISSUE THREAD

**Issue by dcavar** [RMLio/rmlmapper-java#131]
I get this weird tools.jar error, probably from some dependency when using

mvn install

on Win 10 and Mac OS, not on Fedora. Cannot figure out which and why. Anybody some suggestions? Is this some slash vs. backslash issue on Win? What to do about it?

Thanks!

[ERROR] Failed to execute goal on project rmlmapper: Could not resolve dependencies for project be.ugent.rml:rmlmapper:jar:4.12.0: Could not find artifact com.sun:tools:jar:1.7.0 at specified path C:\Java\jdk-17/../lib/tools.jar -> [Help 1]

**Comment by pheyvaer** [comment]
Hi @dcavar 

What is the error message you get when doing it on Mac OS?

**Comment by dcavar** [comment]
[INFO] 
[INFO] -----------------------< be.ugent.rml:rmlmapper >-----------------------
[INFO] Building RMLMapper 4.12.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.473 s
[INFO] Finished at: 2021-09-23T18:36:36-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project rmlmapper: Could not resolve dependencies for project be.ugent.rml:rmlmapper:jar:4.12.0: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by trueg** [comment]
I am getting this on Arch linux, too. Any progress on this one?

**Comment by trueg** [comment]
tools.jar has been removed in jdk 9. Thus, it has to be excluded:

```
diff --git a/pom.xml b/pom.xml
index 34c13ba2..1ed1f656 100644
--- a/pom.xml
+++ b/pom.xml
@@ -273,6 +273,12 @@
<groupId>org.apache.odftoolkit</groupId>
<artifactId>simple-odf</artifactId>
<version>0.8.2-incubating</version>
+            <exclusions>
+            <exclusion>
+                <groupId>com.sun</groupId>
+                <artifactId>tools</artifactId>
+            </exclusion>
+        </exclusions>
</dependency>
<!-- END spreadsheet dependencies-->
</dependencies>
```

**Comment by DylanVanAssche** [comment]
@trueg Your patch is included in the next release, thanks!
@dcavar Does excluding `tools.jar` like @trueg mentioned solve your issue?

**Comment by DylanVanAssche** [comment]
Released, closing.
