### ISSUE TITLE
rmlmapper-java & yarrrml-parser mismatch for escaped delimiter

### ISSUE THREAD

**Issue by florent-andre** [RMLio/rmlmapper-java#137]
* rmlmappper-java use `not escaped \t` : `csvw:delimiter "\t";` : [rmlmappper test](https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/test-cases-CSVW/RMLTC0002a_tabs-CSVW/mapping.ttl)
* yarrrml-parser create `escaped \t` : `csvw:delimiter "\\t";`  [parser test](https://github.com/RMLio/yarrrml-parser/blob/development/test/csv-delimiter/tab/mapping.rml.ttl#L33)
* N3.js library states that this should be an `escaped \t` : [witer test](https://github.com/rdfjs/N3.js/blob/main/test/N3Writer-test.js#L94)
* So it may be a bug in rmlmapper.
 * I don't dive more on that (switching from tsv to csv...), but it may catch your attention

**Comment by DylanVanAssche** [comment]
@pheyvaer Any opinion here?

**Comment by pheyvaer** [comment]
There is an issue for this in YARRRML parser already, I think.

**Comment by florent-andre** [comment]
You are right, [just found it](https://github.com/RMLio/yarrrml-parser/issues/99).

And if I well understand the question you [ask to N3.js](https://github.com/rdfjs/N3.js/issues/221), Yarrrml-parser is true with `escaped \t`. 

To my understanding, rmlmappper-java use `escaped \t` and no more `escaped \t`.

What do you think ?

**Comment by DylanVanAssche** [comment]
@florent-andre 

> What do you think ?

We're waiting for N3.js to fix https://github.com/rdfjs/N3.js/issues/221.
Feel free to comment on the upstream issue.

**Comment by DylanVanAssche** [comment]
Issue was fixed upstream, closing.
