### ISSUE TITLE
Push v4.13.0 to Maven Repository

### ISSUE THREAD

**Issue by JohannesLipp** [RMLio/rmlmapper-java#139]
Hi there! Could you please push the recent version 4.13.0 to [Maven Central](https://mvnrepository.com/artifact/be.ugent.rml/rmlmapper) so that we can use Maven? Thank you so much in advance! 

![image](https://user-images.githubusercontent.com/15930331/144390578-8e56e22e-62c1-4e2b-84a8-92a2f769e629.png)

We are looking forward to the newer version. Thank you.

**Comment by DylanVanAssche** [comment]
Hi!

Yes, we're currently working on it :)
Expect it today or tomorrow.
Thanks!

**Comment by DylanVanAssche** [comment]
It should be available on Maven Central now :)
