### ISSUE TITLE
The release assets for v4.14.3 contain 2 .jar files, which is a sleeping issue for automatically downloading

### ISSUE THREAD

**Issue by mvanbrab** [RMLio/rmlmapper-java#145]
Download code, as found in https://github.com/RMLio/fetch-rmlmapper-java-js and https://github.com/RMLio/rmlmapper-webapi-js for example picks the FIRST a *.jar file asset.

In releases before v4.14.3, rmlmapper only had ONE such asset. Now there are two! Fortunately, the "big" one (including the dependencies) is the first one, so we're lucky, but this can be pure coincidence.

Also, other automatic download implementations might iterate over the assets in reverse order...
It is not a good solution to modify download implementations to search for *-all.jar files, because that is not compatible with all earlier rmlmapper releases...

Suggestion: do not add the "small" one (without depedencies) in next releases.

**Comment by DylanVanAssche** [comment]
Hi @mvanbrab !

Thanks for notifying us about this!
We will adjust the release process to only include the `-all.jar` version.

**Comment by DylanVanAssche** [comment]
Fixed in 4.15.0, closing.
