### ISSUE TITLE
Support variables

### ISSUE THREAD

**Issue by fpompermaier** [RMLio/rmlmapper-java#15]
Is there a way to declare variables in order to reuse them in a mapping?
For example, if I have the root of my doc that contains an attribute with an id, then I could use it in an internal mapping. E.g.

```
<root id="10">
   <children>
      <child id = "1">
```
If I could declare var X = root/@id, then I could declare the subjectMap of child as  htttp://somehost.com/{X}/{id} (this is required in our use case)

**Comment by pheyvaer** [comment]
Hi @fpompermaier 

If you are using XPath you could use [`parent`](https://www.w3schools.com/xml/xpath_axes.asp) to got the parent of "child". Would this work for your use case?

**Comment by fpompermaier** [comment]
If I'm lucky yes, but I fear that there will be the chance that some other variable could be in a non-parent node..that will be more general (and probably faster in terms of performance because it could be accessed very fast using a shared map). Moreover also the mappings would become more readable..
