### ISSUE TITLE
Issue with grel:string_substring

### ISSUE THREAD

**Issue by christinaspachiou** [RMLio/rmlmapper-java#151]
I'm iterating a csv and I'm trying to get the 3 first letters of each country , turn them into lowerCase and apply the output in a URI template. So far I have succeded getting the 3 letters but I cannot apply the result in a template, instead I get the 3 letters code. This is what I've tried

```
rr:predicateObjectMap [
    rr:predicate example:country;
    rr:objectMap [
        fnml:functionValue [
            rr:predicateObjectMap [
               rr:predicate fno:executes ;
               rr:objectMap [ rr:constant grel:string_substring ]
               ] ;

            rr:predicateObjectMap [
             rr:predicate grel:valueParameter ;
             rr:objectMap [ rml:reference "Country of origin" ]
             ] ;

            rr:predicateObjectMap [
             rr:predicate grel:param_int_i_from ;
             rr:objectMap [ rr:constant "0" ]
             ] ;

            rr:predicateObjectMap [
             rr:predicate grel:param_int_i_opt_to ;
             rr:objectMap [ rr:constant "3" ]
             ] ;

            rr:predicateObjectMap [
             rr:predicate grel:stringOut ;
             rr:objectMap [
             rr:template "https://example.com/origin#{Country of origin}"
             ]
          ];
        ]
     ]
];
```

Is it possible to get this triple

` <http://example.com/1> <http://example.com/country>  <http://example.com/origin#fra>` 
  
 instead of   
 
 `<http://example.com/1>  <http://example.com/country>  "Fra";`

**Comment by bjdmeest** [comment]
Templates don't work out of the box with functions, you'll need to 'recreate' the template functionality by nesting this result into a [grel:array_join](https://github.com/RMLio/rml-fno-test-cases/blob/0d51134fe9ffe6910617bf79c06b1cde8feca5ca/RMLFNOTC0023-CSV/mapping.ttl) function (see [here](https://github.com/RMLio/rml-fno-test-cases/blob/master/RMLFNOTC0018-CSV/mapping.ttl) for an example on nesting). Then, you'll probably need to add add `rr:termType rr:IRI` to the objectmap to make sure the array_join result is actually outputted as an IRI and nota a string :)
