### ISSUE TITLE
empty columns of database table are not skipped

### ISSUE THREAD

**Issue by JBPressac** [RMLio/rmlmapper-java#159]
Hello,

As mentioned for CSV files in https://github.com/RMLio/rmlmapper-java/issues/140#issue-1073680736, RmlMapper (v5.0.0.) does not skips triples with empty values from VARCHAR type columns of database tables, resulting in triples like `subject predicate "" .`

Thanks,

**Comment by DylanVanAssche** [comment]
Hi @JBPressac !

Thanks for your issue! We will have a look, did it work differently in previous versions?
