### ISSUE TITLE
rml ontology server down

### ISSUE THREAD

**Issue by bblfish** [RMLio/rmlmapper-java#177]
The name-space for rml in the doc is 
    http://semweb.mmlab.be/ns/rml#
but the server is down.

I checked to see if it was just for me, but not according to this web site:
![Screen Shot 2022-07-11 at 14 29 25](https://user-images.githubusercontent.com/124506/178264381-faa93615-6f4e-4a0f-be7b-e2f0e6bd457f.png)

I could not find a link from the doc to the git repo which would have allowed me to log an issue directly with the right repository. But as this group is using that ontology I guess you know where to look.

**Comment by pheyvaer** [comment]
On my side it works. Maybe it was only down for a brief period?

**Comment by bblfish** [comment]
yep the server is up again and I can get the rml ontology.
 But  I can't get the ql namespace. 

```sh
> curl -i http://semweb.mmlab.be/ns/ql
HTTP/1.1 404 Not Found
Date: Mon, 11 Jul 2022 12:30:55 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 12
ETag: "703595115"
Vary: Accept-Encoding

Nothing here%
```

Intellij has a nice plugin (finally) that allows one to fetch the ontologies to help editing. https://twitter.com/bblfish/status/1513963356641808402

**Comment by bblfish** [comment]
btw. is there a repo for where I should make such a report.
