### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by duschu** [RMLio/rmlmapper-java#18]
Hi,

I would like to use your library in my project. Since I did not find your library to be available in the public Maven repository, I have followed two approaches:

1. Use [jitpack.io](https://jitpack.io/#rmlio/rmlmapper-java) to include the rmlmapper in my Gradle build
2. Use the local Maven repository

Unfortunately, both approaches fail due to the same Maven build error of your library:

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.891 s
[INFO] Finished at: 2018-12-19T15:13:18Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project rmlmapper: Could not resolve dependencies for project be.ugent.rml:rmlmapper:jar:4.1.0: Could not find artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.11.1 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

For a complete log, you can have a look at:

- https://jitpack.io/com/github/rmlio/rmlmapper-java/020094b/build.log
- https://jitpack.io/com/github/rmlio/rmlmapper-java/v4.3.0/build.log

In your most recent release `v4.3.0`, the issue occurs with version 0.12.0 of the `com.github.jsonld-java.jsonld-java` bundle instead of version 0.11.1 as stated above. But this seems to be the equivalent problem.

As I said, the exact issue occurs as well if I locally clone your repository and build the project with `mvn install`.

I tracked down the issue to occur since commit [020094b](https://github.com/RMLio/rmlmapper-java/commit/020094b9c7ab61eebe03f97476cb40a433cac57a), where the `hdt` support has been added. In this commit, the Maven `pom.xml` has been adjusted to include a dependency to the third-party hdt library.
The previous commit [efbd731](https://github.com/RMLio/rmlmapper-java/commit/efbd731153e1ea3eea719f1a00ecc910eeb49af6) can be built succesfully as the corresponding [Jitpack log](https://jitpack.io/com/github/rmlio/rmlmapper-java/efbd731/build.log) also indicates.

Can you please have a look at this build failure. How do you currently build the project without having the same error? Thanks.

**Comment by duschu** [comment]
Including your most recent release .jar file as a local dependency works for me. Nevertheless, I would like to avoid this workaround since this requires me to commit your ~120 MB library to source control. Instead, I would like to let Gradle/Maven handle the dependency resolution dynamically as it is usually done. 

So, it would be really great if you can further investigate the issue. Another solution could be that you push your releases to the public Maven repository. Is that an option to you?

**Comment by ecow** [comment]
I had the the some problem. I used to compile the latest version of docker official image of maven but I get
BUILD FAILURE with mvn clean install.

**Comment by duschu** [comment]
For the resolution of this issue, please have a look at the pull request https://github.com/RMLio/rmlmapper-java/pull/19 and its comments.

**Comment by bjdmeest** [comment]
#19 is merged, and https://jitpack.io/com/github/rmlio/rmlmapper-java/v4.3.2/build.log looks good, so using the latest release (https://github.com/RMLio/rmlmapper-java/releases/tag/v4.3.2) should fix this
