### ISSUE TITLE
ql: ontology not available

### ISSUE THREAD

**Issue by bblfish** [RMLio/rmlmapper-java#181]
I can't get the ql ontology at its namespace 

```sh
> curl -i http://semweb.mmlab.be/ns/ql
HTTP/1.1 404 Not Found
Date: Mon, 11 Jul 2022 12:30:55 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 12
ETag: "703595115"
Vary: Accept-Encoding

Nothing here%
```

Intellij has a nice plugin (finally) that allows one to fetch the ontologies to help editing. And so having the ontologies be avilable as per linked data principles is starting to become really nice. https://twitter.com/bblfish/status/1513963356641808402

**Comment by pheyvaer** [comment]
I think that we never made something available online for this ontology. https://github.com/kg-construct/rml-questions is the best location to follow up on this.

**Comment by DylanVanAssche** [comment]
This ontology will be removed in the RML spec that is being standardized at the W3C Community Group. Closing.
