### ISSUE TITLE
where do I get grelFunctions.jar???

### ISSUE THREAD

**Issue by MartyStache** [RMLio/rmlmapper-java#189]
Greetings!

Where is grelFunctions.jar? 

I've got the RMLMapper-webservice-api (Docker) up and running and running transformations successfully...

Now, I am attempting to organize everything I need to execute grel functions...I see it needs to be referenced in the formulas .ttl declaration file. I assume it needs to sit besides RMLMapper.jar when creating the image?

There is a LOT of GREAT documentation on how to configure the execution of functions properly, but I cannot find any information indicating location to acquire the .jar. Unless I am missing something (and it is already included in the RMLMapping.jar?

Any help is greatly appreciated!!

**Comment by MartyStache** [comment]
I believe I have found the .jar is located here under releases:

https://github.com/FnOio/grel-functions-java

**Comment by bjdmeest** [comment]
You're correct! https://github.com/FnOio/grel-functions-java is from where the jar is built :)
