### ISSUE TITLE
Typo in $3.3 prefix of wgs84_pos

### ISSUE THREAD

**Issue by gatemezing** [RMLio/rmlmapper-java#195]
In the document at https://rml.io/specs/rml/, section 3.3, there is a typo in the namespace of  `wgs84_pos`. It is written 
`@prefix wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#lat> `instead of `@prefix wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>` like in other sections of the same document. (e.g., section 3.1) 
Thanks for your great work.

**Comment by DylanVanAssche** [comment]
Thanks for the feedback! I will correct the typo in the spec :)
