### ISSUE TITLE
CSV on the Web description implementation

### ISSUE THREAD

**Issue by ecow** [RMLio/rmlmapper-java#20]
Hi,
are there any plan for implementing the support of  csvw:Table as rml:source in logical source?

Are there alternatives to customize separator and other dialect related properties (e.g. encoding and header presence) in parsing csv?

**Comment by pheyvaer** [comment]
Hi,

Yes we have it on our list for future features, but unfortunately, we don't support other alternatives at the moment to specify the separator and other dialect related properties.

**Comment by bjdmeest** [comment]
Hi, our new [v4.4.0 release](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.4.0) supports CSVW dialects, see example files in https://github.com/RMLio/rmlmapper-java/tree/master/src/test/resources/test-cases-CSVW
