### ISSUE TITLE
RML Mapper does not accept files in Windows (CRLF)

### ISSUE THREAD

**Issue by Shghazy** [RMLio/rmlmapper-java#201]
I have tried using the mapper to map GTFS data from csv / txt files to RDF. When the mapping file is set in Windows (CRLF), the mapper does not work and gives an error "Unable to parse mapping rules as Turtle. Does the file exist and is it valid Turtle?" 

The same file, however, does work if converted to Unix (LF). Can the mapper be made to accommodate CRLF?

**Comment by bjdmeest** [comment]
Could you provide the exact file that gives the problem, and your converted file? I develop in Windows so all my mapping files are in CRLF. Could it be that your conversion does some more things, e.g. removing the BOM?

**Comment by DylanVanAssche** [comment]
@bjdmeest This is not the mapping file, but the original CSV file that is being mapped. Do we handle that case as well?
