### ISSUE TITLE
Large csv input used with rmlmapper

### ISSUE THREAD

**Issue by titoarrabal** [RMLio/rmlmapper-java#203]
Hi! Im trying to use rmlmapper over my csv files (1.400.000 rows), but it doesnt give any output because it keeps thinking. Is there another rmlToRdf conversor which could make that job? 
Thank you!

**Comment by titoarrabal** [comment]
RML streamer gives me an error, and I dont know how to solve it. I leave the error here!
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at io.rml.framework.Main$.main(Main.scala:124)
        at io.rml.framework.Main.main(Main.scala)

**Comment by bjdmeest** [comment]
Could you provide the mapping file and cli arguments you're using to try
the rmlstreamer? It should be able to handle this amount of data :)

Op ma 15 mei 2023 19:48 schreef titoarrabal ***@***.***>:

**Comment by titoarrabal** [comment]
[Meteorologicos.zip](https://github.com/RMLio/rmlmapper-java/files/11487828/Meteorologicos.zip)
I am using yarrrml-paser to obtain map1.rml.ttl. Then, i use this command:
**java -jar rmlstreamer.jar toFile --mapping-file C:/Users/Usuario/Desktop/TFG/Mapping/ComunidadMadrid/Meteorologicos/map1.rml.ttl --output-path  prueba.nt**
It gives me this error
![image](https://github.com/RMLio/rmlmapper-java/assets/72153934/fa6d94b5-7c2f-4b4c-9596-041e846ecf18)

**Comment by bjdmeest** [comment]
@ghsnd ?

**Comment by ghsnd** [comment]
Hi! Did you try the [standalone version](https://github.com/RMLio/RMLStreamer/releases/download/v2.4.2/RMLStreamer-2.4.2-standalone.jar) of RMLStreamer? It looks like this is the version that has to be deployed on a Flink cluster.

**Comment by DylanVanAssche** [comment]
No response for a while, re-open if needed
