### ISSUE TITLE
Validate Xpath with prefix whose namespace is declared in the child tag & not in the root tag.  prefix, which is not declared in the root element.

### ISSUE THREAD

**Issue by nilimamoh** [RMLio/rmlmapper-java#204]
Validate Xpath with prefix whose namespace is declared in the child tag & not in the root tag.
 however xpath expression does not work here. any suggestions 

namespace resolver resolved only root tags namespace

**Comment by DylanVanAssche** [comment]
No response for a while, re-open if needed
