### ISSUE TITLE
how to change input file

### ISSUE THREAD

**Issue by gsilvestri1234** [RMLio/rmlmapper-java#205]
Hi to all i'm new of rmlmapper and i don't find how to change the default path for input source called inputSourceFile.json. is it possibile? How i can change it?

Thanks in advance!

**Comment by DylanVanAssche** [comment]
The input source path is set in the RML mapping rules, there you can change it.

Example:

```
<#TransportMapping> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "Transport.xml" ;
    rml:iterator "/transport/bus/route/stop";
    rml:referenceFormulation ql:XPath;
  ];

  rr:subjectMap [
    rr:template
      "http://trans.example.com/stop/{@id}";
    rr:class ex:Stop
  ];

  rr:predicateObjectMap [
    rr:predicate rdfs:label;
    rr:objectMap [
      rml:reference "."
    ]
  ].
```

--> `rml:source "Transport.xml" ;` here is the path set to `Transport.xml`.
