### ISSUE TITLE
Docker build error: Could not resolve dependencies for project be.ugent.rml:rmlmapper:jar:6.1.3

### ISSUE THREAD

**Issue by PrzemyslawSagalo** [RMLio/rmlmapper-java#208]
Hello,

I have come across an issue during the process of building a Docker image locally. 
The message of the error is displayed below:
`[ERROR] Failed to execute goal on project rmlmapper: Could not resolve dependencies for project be.ugent.rml:rmlmapper:jar:6.1.3: Failed to collect dependencies at com.github.rdfhdt:hdt-java:jar:v3.0.5 -> com.github.rdfhdt.hdt-java:hdt-java-cli:jar:v3.0.5 -> com.github.rdfhdt.hdt-java:hdt-java-core:jar:v3.0.5 -> org.visnow:JLargeArrays:jar:1.7-20220624.150242-7: Failed to read artifact descriptor for org.visnow:JLargeArrays:jar:1.7-20220624.150242-7: Could not transfer artifact org.visnow:JLargeArrays:pom:1.7-20220624.150242-7 from/to gitlab-maven (https://gitlab.com/api/v4/projects/375779/packages/maven): Transfer failed for https://gitlab.com/api/v4/projects/375779/packages/maven/org/visnow/JLargeArrays/1.7-SNAPSHOT/JLargeArrays-1.7-20220624.150242-7.pom: Connection reset -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command '/bin/sh -c mvn clean install -DskipTests=true' returned a non-zero code: 1`

**Comment by DylanVanAssche** [comment]
I tested this locally on the `development` branch and building is fine here. Can you please try again?

**Comment by s33kers** [comment]
We are using RMLMapper as a dependency in our project, however, we cannot upgrade to >6.0.0 version as getting error  `Could not find org.visnow:JLargeArrays:1.7-20220624.150242-7`

**Comment by DylanVanAssche** [comment]
Please re-open if you still have issues, closing after no response for a while.
