### ISSUE TITLE
Reoccurrence of past issue regarding "empty cells from CSV input not getting skipped" in rmlmapper 6.1.3 

### ISSUE THREAD

**Issue by nayaksnigdha** [RMLio/rmlmapper-java#209]
Hello Dev Team,

I am using stanalone version of rmlmapper-6.1.3-r367-all.jar on Windows 10 machine.

I am facing the issue regarding empty cells in input CSV input not getting skipped. 

If my input CSV has empty values, the tool execution fails with ArrayIndexOutOfBounds Exception from CSVRecord.java

As per R2RML spec here : https://www.w3.org/TR/r2rml/ (section 11.1) empty is valid input.

This issue has been reported and fixed in the past (https://github.com/RMLio/rmlmapper-java/issues/140), but still resurfaces with 6.1 version.

**Comment by DylanVanAssche** [comment]
Do you have maybe an example for us:

- mapping file
- input data file
- CLI output

?

Thanks!

**Comment by nayaksnigdha** [comment]
Hello Dylan,

Please find attached the files (input csv, console error snapshot, mappings file) you requested. 
[logs.zip](https://github.com/RMLio/rmlmapper-java/files/11936104/logs.zip)

During my initial investigation I found that the issue is because of empty value in last column of csv file. If I provide a dummy value, output is generated successfully.
