### ISSUE TITLE
rr:Template does not URLfy strings

### ISSUE THREAD

**Issue by mariapoveda** [RMLio/rmlmapper-java#21]
When using the template construct in a predicate object map the json values are not URLfied as when using the same expression in a subject map.

Predicate object map example:

  rr:predicateObjectMap [
    rr:predicate etvonto:hasForm;
    rr:objectMap [
      rr:template "http://easytv.linkeddata.es/resource/LinguisticExpressionItem/{Sls}{Url}{Word}";
      rr:termType rr:IRI
    ]
  ]

Resulting Triple (see difference between subject and predicate generation):

<http://easytv.linkeddata.es/resource/SignedLinguisticExpression/this%20movie%20three%20I%20have%20seen%20timeshttps%3A%2F%2Fmedia.spreadthesign.com%2Fvideo%2Fmp4%2F1%2F105750.mp4> <https://w3id.org/def/easytv#decomposition> <http://easytv.linkeddata.es/resource/LinguisticExpressionItem/this movie three I have seen timeshttps://media.spreadthesign.com/video/mp4/1/105750.mp41> null

**Comment by pheyvaer** [comment]
Hi @mariapoveda,

We've confirmed the bug and fixed it locally. The fix will be available in the next release. We'll keep you up to date! Thanks for reporting :+1:

**Comment by mariapoveda** [comment]
Thanks @pheyvaer 

Do you have already planned the next release?

**Comment by pheyvaer** [comment]
Normally, we will have a new release next week :smiley:

**Comment by mariapoveda** [comment]
Cool, thanks.

**Comment by bjdmeest** [comment]
@mariapoveda , our new release (https://github.com/RMLio/rmlmapper-java/releases/tag/v4.3.2) contains the fix to this issue, thanks again for notifying!
