### ISSUE TITLE
Example 3.1 from the RML Spec

### ISSUE THREAD

**Issue by vchaudhri** [RMLio/rmlmapper-java#213]
I tried to run the example 3.1 from the spec, but it fails with the following cryptic error:

$ java -jar rmlmapper-6.2.1-r368-all.jar -m 3.1.rml -o 3.1.ttl
17:41:37.748 [main] ERROR be.ugent.rml.cli.Main               .run(416) - Mapping for id not found, expected one of [null]

Other examples run just fine, so I believe that my setup is correct and there might be some issue with the mapping rules.

**Comment by DylanVanAssche** [comment]
Hi!

Apologies for the late reply. Could you upload here the mapping and input data you used?
