### ISSUE TITLE
README: Deduplication option only affects nquads and hdt serialization

### ISSUE THREAD

**Issue by nicolastoira** [RMLio/rmlmapper-java#214]
Hi,
I was wondering if the deduplication -d does have any effect on the data when serialization -s turtle is activated, or if the two features are completely decoupled. Thank you.

**Comment by bjdmeest** [comment]
Deduplication is actually by default for all serializations except nquads or hdt, so it has no effect on the turtle serialization.
I'm keep this open to update our readme! :)

**Comment by nicolastoira** [comment]
Great thanks. Is this also true for older versions? Especially for version `rmlmapper-6.0.0-r363-all`?

**Comment by bjdmeest** [comment]
As far as I know, this is the same behavior since at least 4.8.2
