### ISSUE TITLE
Dependency resolution of rmlmapper 6.2.1 fails

### ISSUE THREAD

**Issue by IanEmmons** [RMLio/rmlmapper-java#215]
When I try to use rmlmapper as a library (via the gradle dependency 'be.ugent.rml:rmlmapper:6.2.1'), gradle is unable to resolve the following dependencies against MavenCentral:

- com.github.rdfhdt:hdt-java:v3.0.5
- com.github.FnOio:function-agent-java:v1.1.0
- com.github.fnoio:grel-functions-java:v0.9.1
- com.github.fnoio:idlab-functions-java:v1.0.0

When I add the artifact repository 'https://jitpack.io', gradle successfully resolves the four above, but is unable to resolve this one:

- org.visnow:JLargeArrays:1.7-20220624.150242-7

Which is pulled in via the following dependency chain:

- be.ugent.rml:rmlmapper:6.2.1
  - com.github.rdfhdt:hdt-java:v3.0.5
      - com.github.rdfhdt.hdt-java:hdt-java-core:v3.0.5

Is there another Maven repository that I need? Or is there a library you forgot to publish? Or is something more subtle going on?

**Comment by bjdmeest** [comment]
We'll look into this (because it's at least weird that this isn't happening locally or in our CI processes), but I suggest that you also follow-up on the [RDFHDT github](https://github.com/rdfhdt/hdt-java): I would expect the proper fix to be something on their end (given it's a dependency of rdfhdt that doesn't resolve)

**Comment by IanEmmons** [comment]
Thanks. I've submitted https://github.com/rdfhdt/hdt-java/issues/198. One further note: I discovered that MavenCentral has a library under the designation 'org.rdfhdt:hdt-java-core:3.0.5' (with latest version 3.0.9). That runs into the same problem with JLargeArrays, however. But it may be the case that your hdt-java dependency is not using the preferred organization ID. (I've asked this in the issue above.)

**Comment by IanEmmons** [comment]
The rdfhdt team put out a new release, in which they removed JLargeArrays and replaced it with their own implementation. They recommend that you change your rdfhdt dependency from 'com.github.rdfhdt.hdt-java:hdt-java:v3.0.5' to 'org.rdfhdt:hdt-java-core:3.0.10'. Notice the change in group ID — this means the dependency will come from MavenCentral rather than 'https://jitpack.io', which is a happy thing.

**Comment by IanEmmons** [comment]
Given the new 3.0.10 rdfhdt release, it seems to me that the path forward would be for the RMLMapper team to update that dependency and release version 6.2.2. Just so I can best decide how to move forward with my work, could you please comment on whether that's correct and what your estimated timeline looks like? Sorry to nag, but in the near it changes my best path forward term quite a bit.

**Comment by DylanVanAssche** [comment]
We can update the dependency. Could you verify then from the `development` branch if your problem is fixed?

**Comment by IanEmmons** [comment]
Sure, I can do that. But I can already report that if I create a test project with a dependency on 'org.rdfhdt:hdt-java-core:3.0.10' then the dependency resolution works, whereas the similar experiement with 'com.github.rdfhdt.hdt-java:hdt-java:v3.0.5' reproduced the problem with resolving the JLargeArrays library. This should raise your confidence that the updated dependency will work. Let me know when you are ready for me to test.

**Comment by DylanVanAssche** [comment]
@IanEmmons Thanks! Pushed a commit to the dev branch. Once tested, we can close this.

**Comment by IanEmmons** [comment]
@DylanVanAssche Yes, it checks out. I am able to build against this version. I look forward to seeing 6.2.2 released soon-ish, though I have a workaround with my local build, so it's no emergency.

**Comment by DylanVanAssche** [comment]
Awesome! Thanks for confirming @IanEmmons !
