### ISSUE TITLE
Generating and IRI from an email address

### ISSUE THREAD

**Issue by psiotwo** [RMLio/rmlmapper-java#216]
I need to turn a value like 'a@example.com' into an IRI `<a@example.com>`:

- `rr:objectMap [ rml:reference "email" ]` - generates a literal `"a@example.com"`
- `rr:objectMap [ rml:reference "email" ; rr:termType rr:IRI ]` - generates an IRI prepended with BASE, i.e.  `<https://some-base-of-the-document/a@example.com>`

But I need `<a@example.com>`.

Is it possible? If yes, how? Thanks a lot.

**Comment by DylanVanAssche** [comment]
The IRI must be a valid one, yours:

```
<a@example.com>
```

Is not really a valid one.
If the IRI is not an absolute one, the [R2]RML specification [1] specifies that the base IRI of the mapping should be used to get an absolute IRI. This is what you see here.

```
<mailto:a@example.com>
```
This should be a valid absolute IRI, thus the base IRI is not put in front then.

[1] https://www.w3.org/TR/r2rml/
