### ISSUE TITLE
Feature request: string replace function

### ISSUE THREAD

**Issue by MathiasVDA** [RMLio/rmlmapper-java#223]
Hello,

I'm not sure if this is the right place for it, but I have a feature request. The [currently supported](https://rml.io/docs/rmlmapper/default-functions/) don't include a string replace function. I found this out when I tried to map the value "76 cm" to "76"^^xsd:decimal

I know it's possible to [extend the set of function available in RML](https://github.com/RMLio/rmlmapper-java#including-functions), but I think nearly everyone will be in need of this particular function. 

Thanks!

**Comment by DylanVanAssche** [comment]
Hi,

Hmmmm that might be desired yes :)
It seems that there's already support for this in the GREL family of functions: https://github.com/FnOio/grel-functions-java/blob/90c1ddabe26d371ac1e45d91f6f7698d6519247a/src/main/resources/grel_java_mapping.ttl#L442

However, it doesn't seem documented?

CC: @ghsnd

**Comment by ghsnd** [comment]
Hhmm, there is a bug in generating the rmlio website, preventing GREL functions to be documented. Fixing it...

**Comment by DylanVanAssche** [comment]
Website has been fixed for some time, see https://rml.io/docs/rmlmapper/default-functions/
