### ISSUE TITLE
update the main readme

### ISSUE THREAD

**Issue by m1ci** [RMLio/rmlmapper-java#23]
at https://github.com/RMLio/rmlmapper-java
there is no info that turtle output format is also supported, please update the readme

**Comment by pheyvaer** [comment]
Hi @m1ci,

Indeed, you're right. We will update the README. Thanks for letting us know!

**Comment by bjdmeest** [comment]
Fixed in the latest release! https://github.com/RMLio/rmlmapper-java/releases/v4.3.3
