### ISSUE TITLE
RMLMapper v6.5.1 doesn't generate all triples

### ISSUE THREAD

**Issue by dachafra** [RMLio/rmlmapper-java#234]
We tested a very simple mapping and data with the combination of two columns for the subject generation and the last version of the engine generates 852 triples, and when we run it with the v6.2.2 generates 563082 triples (93417 if we remove the duplicates).

We attached the mapping and the data we are using.

/cc @OscarHid
 
[resources.zip](https://github.com/RMLio/rmlmapper-java/files/14916166/resources.zip)

**Comment by DylanVanAssche** [comment]
7.0.0 was released which refactors a lot, could you please try it? Thanks!

**Comment by DylanVanAssche** [comment]
I tested this with 7.0.0 and got 93417 triples, closing as this is what is expected :)
