### ISSUE TITLE
Support for Json Keys

### ISSUE THREAD

**Issue by alloka** [RMLio/rmlmapper-java#246]
Hello everyone, 

so I have the following Json file: `[{"type":"node","id":"0","labels":["Sport"],"properties":{"sport_id":100,"sport_name":"Tennis"}},{"type":"node","id":"1","labels":["Student"],"properties":{"name":"Demi Moore","id":20}},{"type":"node","id":"7","labels":["Student"],"properties":{"name":"Venus Williams","id":10}},{"type":"relationship","id":"0","label":"practises","properties":{"duration":10},"start":{"id":"7","labels":["Student"],"properties":{"name":"Venus Williams","id":10}},"end":{"id":"0","labels":["Sport"],"properties":{"sport_id":100,"sport_name":"Tennis"}}},{"type":"relationship","id":"1","label":"practises","properties":{"duration":20},"start":{"id":"1","labels":["Student"],"properties":{"name":"Demi Moore","id":20}},"end":{"id":"0","labels":["Sport"],"properties":{"sport_id":100,"sport_name":"Tennis"}}}]` 

and I was wondering if there is a way using the json path $.properties.[`*`].~ to reference the properties keys in this json file. something like $.properties.[*].~ in order to get properties as sport_id and sport_name without prior knowledge of them

Best regards,
Ali.

**Comment by DylanVanAssche** [comment]
No, that is not possible, this is not possible with JSONPath. This is a JSONPath limitation, XPath can do it.
