### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by jetztgradnet** [RMLio/rmlmapper-java#25]
Dear RMLio team,

unfortunately this repository does not contain a LICENSE file, so it's unclear under which license this project is released. 

Would you please add a license file? Apache and MIT are great choices, as they make this library widely usable, but that's of course the choice of the owner.

Thanks,
Wolfgang

**Comment by pheyvaer** [comment]
Hi @jetztgradnet 

The RMLMapper is available under the MIT license. We will add the LICENSE file in the next release.

**Comment by bjdmeest** [comment]
fixed in the latest release! https://github.com/RMLio/rmlmapper-java/releases/v4.3.3
