### ISSUE TITLE
GrelFunctions.jar source ?

### ISSUE THREAD

**Issue by akuckartz** [RMLio/rmlmapper-java#26]
Where is this file coming from?
https://github.com/RMLio/rmlmapper-java/blob/master/src/main/resources/GrelFunctions.jar

**Comment by pheyvaer** [comment]
The code for this jar can be found [here](https://github.com/RMLio/rmlmapper-java/blob/master/src/main/java/be/ugent/rml/functions/lib/GrelProcessor.java).

**Comment by wetneb** [comment]
I am working on exposing GREL's implementation as a Maven artifact. A preview of what this will look like can be found in the `4.x` branch of the OpenRefine repository:
https://github.com/OpenRefine/OpenRefine/tree/4.x

**Comment by bjdmeest** [comment]
@wetneb that's sincerely awesome. Could you let us know when it's available on Maven? Then we can abandon our own code of https://github.com/FnOio/grel-functions-java and focus on purely integrating your 'real' implementation using https://fno.io :)

**Comment by wetneb** [comment]
Sure, adding a note in the issue to notify you when it is out.
