### ISSUE TITLE
rmlmapper not generating outputfile when mapping the first column of input file

### ISSUE THREAD

**Issue by FloortjeWijnands** [RMLio/rmlmapper-java#27]
As requested in a previous issue:

rmlmapper is not producing an output file even though there are no errors given (or with the newest version of rmlmapper, it produces errors saying that there are no variables to complete the template). After trouble shooting I found out that rmlmapper seems to have issues when variables are in the first column of the input file. This issue was resolved for two inputfiles when I simply added a random first column to the data. 

[Files.zip](https://github.com/RMLio/RML-Mapper/files/2957136/Files.zip)

**Comment by pheyvaer** [comment]
Hi @FloortjeWijnands,

Sorry for the late reply. I've tested it with the latest version of the RMLMapper and the problem is not present there. Could you try again? If you still have the same problem, you can reopen the issue.
