### ISSUE TITLE
Output Format

### ISSUE THREAD

**Issue by venkateshzifo** [RMLio/rmlmapper-java#29]
Hi,

How to set the output format using the java code. I am getting the output as RDF triples now. I would like to get the output as JSON-LD. I would like to do this from the code. Do we need to define it somewhere with executor object ? Could you please help me on this ?

**Comment by bjdmeest** [comment]
Hi,

The `executor.execute`-command returns a QuadStore, which has a `write` method that takes the format as one of the parameters. For example, the snippet below writes the output as jsonld to stdout.

```
QuadStore result = executor.execute(triplesMaps, checkOptionPresence(removeduplicatesOption, lineArgs, configFile), metadataGenerator);
BufferedWriter out = new BufferedWriter(new OutputStreamWriter(System.out));
result.write(out, "jsonld");
```

Does this help?

**Comment by venkateshzifo** [comment]
Thanks for the response. 

Yeah that's what I am looking for. But its not working

It throws **Serialization jsonld not supported** when I try to write the output as jsonld.

**Comment by bjdmeest** [comment]
Ah, could it be that you are using a `SimpleQuadStore` instead of a `RDF4JStore` when creating the `Executor`?

```
Executor executor = new Executor(rmlStore, factory, functionLoader, outputStore, Utils.getBaseDirectiveTurtle(is));
```
The `outputStore` of this line should be an `RDF4JStore`.

**Comment by venkateshzifo** [comment]
I am using below code snippet. I am using RDF4JStore only.

`InputStream mappingStream = new FileInputStream(chromatographyMappingFile);
			Model model = Rio.parse(mappingStream, "", RDFFormat.TURTLE);

			RDF4JStore outputStore = new RDF4JStore(model);

			Executor executor = new Executor(outputStore, new RecordsFactory(new DataFetcher(cwd, outputStore)));
			QuadStore chromResult = executor.execute(executor.getTriplesMaps());
			chromResult.removeDuplicates();

			BufferedWriter out = new BufferedWriter(new OutputStreamWriter(System.out));
			chromResult.write(out, "jsonld");`

**Comment by bjdmeest** [comment]
Ah, yes, there's a bit of confusion here: you need QuadStore for your RML mapping, and a second QuadStore for your output data. You can check https://github.com/RMLio/rmlmapper-java/blob/master/src/main/java/be/ugent/rml/cli/Main.java for more details, but I guess you need something along the lines of

```java
// Read mapping file
InputStream mappingStream = new FileInputStream(mappingFile);
Model model = Rio.parse(mappingStream, "", RDFFormat.TURTLE);
RDF4JStore rmlStore= new RDF4JStore(model);
// Load functions
FunctionLoader functionLoader = new FunctionLoader(null, null, new HashMap<>());
// Prepare output store
RDF4JStore outputStore = new RDF4JStore();
// Create executor
Executor executor = new Executor(rmlStore, new RecordsFactory(new DataFetcher(cwd, rmlStore)),functionLoader, outputStore, Utils.getBaseDirectiveTurtle(mappingStream ));
// Execute
QuadStore chromResult = executor.execute(executor.getTriplesMaps());
chromResult.removeDuplicates();
// Write result
BufferedWriter out = new BufferedWriter(new OutputStreamWriter(System.out));
chromResult.write(out, "jsonld");`
```

**Comment by venkateshzifo** [comment]
I am facing new problem with this code. Utils.getBaseDirectiveTurtle is not available method in Utils class. Is this from be.ugent.rml.Utils class ?

**Comment by bjdmeest** [comment]
Indeed, please see https://github.com/RMLio/rmlmapper-java/blob/master/src/main/java/be/ugent/rml/cli/Main.java for the imports

**Comment by venkateshzifo** [comment]
Thanks, It worked, the problem is, I was using older jar. Thanks for helping out :)
