### ISSUE TITLE
JDBC connectors

### ISSUE THREAD

**Issue by cordawyn** [RMLio/rmlmapper-java#30]
Hi!

Is there some preference for using `DriverManager` instead of `DataSource` for JDBC connections in `RDBs.java`?

The reason for asking is that I had to connect to a certain (non-default) schema in postgres DB, and it is recommended to specify the schema name as a param in the JDBC connection string as follows: `jdbc:postgresql://localhost:5432/database?currentSchema=sc1`. If I use this URL for "jdbcDSN", then it doesn't work – because treating it as a simple string in https://github.com/RMLio/rmlmapper-java/blob/88ff0436edeccf2ef9b581d5bbc38997e97122a1/src/main/java/be/ugent/rml/records/RDBs.java#L36 creates an invalid URL (with two "?"s).

With `DataSource` one doesn't have to make user and password a part of the URL as above – instead, it provides somewhat uniform API for setting those params without having to "manually" manipulate `jdbcDSN`. It also seems to be a preferred method of dealing with JDBC connections, as stated in https://docs.oracle.com/javase/10/docs/api/java/sql/DriverManager.html

So... I could try and refactor that part of JDBC-related code to use `DataSource`, if there's no objections :) Provided, I have some time to spare soon.

**Comment by bjdmeest** [comment]
Hi @cordawyn, sorry for only getting back to you now. And no: there's no specific preference for using `DriverManager`. Afaict, functionally your proposed change wouldn't change anything, or make it even more robust, so there would be no objections to a pull request! :)
