### ISSUE TITLE
Log lines should be printed to stderr, not to stdout

### ISSUE THREAD

**Issue by hidde-jan** [RMLio/rmlmapper-java#31]
Without an `--outputfile`, the CLI prints the resulting serialized facts to stdout. Since the logs are also printed to stdout, you can't directly use the resulting output without filtering out logging information.

Log lines should be printed to stderr instead.

**Comment by pheyvaer** [comment]
Hi @hidde-jan We fixed this internally and it will be available in the next release :smiley:.
