### ISSUE TITLE
JAR file usage issues

### ISSUE THREAD

**Issue by venkateshzifo** [RMLio/rmlmapper-java#32]
Hi,

I am using rmlmapper.jar in my spring boot maven project. 

I am facing an issue where I am not able to ignore the SLF4J jar which rmlmapper refers to. 

Need you help in ignoring the Spring and SLF4J classes from the rmlmapper.jar file.

I am not able to run this as a WAR file as the classpath has multiple bindings for SLF4J and DispatcherServlet class.

Thanks,
Venkatesh

**Comment by pheyvaer** [comment]
Hi Venkatesh,

Could you give a bit more information? What is the exact error you are getting? And is this an issue related to the RMLMapper or to Maven?

**Comment by venkateshzifo** [comment]
When I generate WAR file with maven and run in tomcat server, I got error message saying classpath contains multiple slf4j bindings, then I tried excluding the SLF4J jar in rmlmapper dependency as below.

<dependency>
	<groupId>java</groupId>
	<artifactId>rmlmapper</artifactId>
	<version>4.3.3</version>
	<exclusions>
		<exclusion>
			<artifactId>slf4j-api</artifactId>
			<groupId>org.slf4j</groupId>
		</exclusion>
	</exclusions>
</dependency>

But I was getting same error. I am not able to exclude any dependent jars from rmlmapper jar file. I tried excluding in the spring boot dependency and the error went away, but new error came saying found multiple DispatcherServlet class bindings. How can I exclude dependent jars from rmlmapper jar file in maven project.

**Comment by bjdmeest** [comment]
Hi Ventakesh, it's hard to identify whether this is an RMLMapper issue or a pom issue without further context or stack trace, it does seem to occur in other projects as well (https://stackoverflow.com/questions/38897655/slf4j-class-path-contains-multiple-slf4j-bindings-after-excluding-logback). Could you send us the error stack trace?

**Comment by venkateshzifo** [comment]
Is it possible to share an example of how to use this jar inside a Spring Boot project ? I have tried every possible thing with maven but no success.

**Comment by ghsnd** [comment]
I have successfully added a depencency to the RMLMapper in a Spring Boot project and it boots.

Note that the depenceny is

```xml
        <dependency>
            <groupId>be.ugent.rml</groupId>
            <artifactId>rmlmapper</artifactId>
            <version>4.4.0</version>
        </dependency>
```

**Comment by venkateshzifo** [comment]
Is this available in central maven repository ?

**Comment by bjdmeest** [comment]
Ah, no, but using it as a [jitpack.io](jitpack.io) dependency should work

**Comment by venkateshzifo** [comment]
I have added the repository as below, but dependency is not downloading

```
<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

**Comment by venkateshzifo** [comment]
Could you please share your pom file ? It will be very helpful to fix this.

**Comment by ghsnd** [comment]
I had to rename the file so GitHub would accept it, but here it is.

[pom.xml.txt](https://github.com/RMLio/rmlmapper-java/files/3187610/pom.xml.txt)

**Comment by venkateshzifo** [comment]
Where the repositories are mentioned in this file ? I don't see any repositories mentioned here. Then how the maven will fetch the dependencies ?

**Comment by bjdmeest** [comment]
There seems to be a bit of confusion: I assume the pom given by @ghsnd will be usable when the rmlmapper is installed locally, when using https://jitpack.io, the pom will be different, please see the jitpack website https://jitpack.io/#RMLio/rmlmapper-java/4.4.0:

```
        <repositories>
                <repository>
                    <id>repo.maven.apache.org</id>
                    <url>https://repo.maven.apache.org/maven2/</url>
                </repository>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
[...]
	<dependency>
	    <groupId>com.github.RMLio</groupId>
	    <artifactId>rmlmapper-java</artifactId>
	    <version>4.4.0</version>
	</dependency>
```

**Comment by venkateshzifo** [comment]
It gets downloaded, but still i am facing below issue 

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Venkatesh.k/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Venkatesh.k/.m2/repository/com/github/rmlio/rmlmapper-java/4.4.0/rmlmapper-java-4.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]

**Comment by bjdmeest** [comment]
So, this certainly feels like a maven/pom.xml or SLF4J issue at this point. Solutions as suggested in https://www.slf4j.org/codes.html#multiple_bindings should help you further.

**Comment by venkateshzifo** [comment]
I have excluded the slf4j like below, still no success

```
<dependency>
		    <groupId>com.github.RMLio</groupId>
		    <artifactId>rmlmapper-java</artifactId>
		    <version>4.4.0</version>
		    <exclusions>
		        <exclusion>
		            <artifactId>slf4j-api</artifactId>
		            <groupId>org.slf4j</groupId>
		        </exclusion>
		        <exclusion>
		            <artifactId>jcl-over-slf4j</artifactId>
		            <groupId>org.slf4j</groupId>
		        </exclusion>
		    </exclusions>
		</dependency>
```

**Comment by bjdmeest** [comment]
As suggested before in https://stackoverflow.com/questions/38897655/slf4j-class-path-contains-multiple-slf4j-bindings-after-excluding-logback, I would use `mvn dependency:tree` to see exactly which dependencies are creating the issue and keep excluding until the issue resolves. Or, ignore it as suggested by https://www.slf4j.org/codes.html#multiple_bindings, as it's just a warning ;). I will close this issue as it is not specific to the RMLMapper
