### ISSUE TITLE
RDF Mapping Relationships (parentTriplesMap, child, parent ...)

### ISSUE THREAD

**Issue by AkbarKazimov** [RMLio/rmlmapper-java#36]
Hi. Is there any tutorial or anything else that explains relationships in Rdf Mapping other than this--(http://rml.io/spec.html#relationships-among-logical-sources-rr-parenttriplesmap-rr-joincondition-rr-child-and-rr-parent (Chapter 7)).

**Comment by pheyvaer** [comment]
Hi,

You can have a look at [this](http://rml.io/yarrrml/tutorial/getting-started/#how-to-link-two-entities). It's a tutorial for YARRRML (a human readable text-based representation for declarative knowledge graph generation rules). YARRRML rules can be converted to RML rules. As part of the tutorial, we explain how entities can be linked. Users don't need to know about parentTriplesMaps, and so on. I hope this helps.

**Comment by AkbarKazimov** [comment]
Thank you
