### ISSUE TITLE
IRIs support

### ISSUE THREAD

**Issue by mariapoveda** [RMLio/rmlmapper-java#37]
Are IRI supported?

We are having issues to generate mappings in which the subjects are like http://babelnet.org/rdf/θερμότητα_EL/s00043417n

When it appears in the object is fine.

**Comment by pheyvaer** [comment]
Hi Maria,

Yes they are. What specific issues are you having? Are they not appearing at all or are there encoding issues?

**Comment by mariapoveda** [comment]
The triples with that IRI in the subject do not appear at all.

**Comment by pheyvaer** [comment]
This is probably due to the validation of the URLs, which might fail on your example. We are looking into it.

**Comment by mariapoveda** [comment]
Hello Pieter,

   is there any decision about this? Do you need the specific example mapping where I'm having this issue?

Best,

María

**Comment by pheyvaer** [comment]
Hi María,

We fixed the issue. We will release a new version today! :smile:

**Comment by pheyvaer** [comment]
Hi María,

The [new version](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.5.0) is available. Can you try and see if your issue is fixed?

**Comment by mariapoveda** [comment]
Sure! I'll try a.s.a.p. Thank you very much.

**Comment by hridaydutta123** [comment]
@mariapoveda Is the newer version working?

**Comment by mariapoveda** [comment]
Yes. @SerPablo could you confirm too?

**Comment by hridaydutta123** [comment]
@mariapoveda Can you please share with us the mapping file and source file? We are also facing the same issue.

**Comment by SerPablo** [comment]
[source.zip](https://github.com/RMLio/rmlmapper-java/files/3486035/source.zip)
[mapperFile.zip](https://github.com/RMLio/rmlmapper-java/files/3486037/mapperFile.zip)

**Comment by hridaydutta123** [comment]
Thanks @SerPablo. I will check them and let you know.

**Comment by prashantimaktala** [comment]
Hello @SerPablo,

I used the mapper file and source file to convert it to rdf file. When I load the output RDF file into neo4j I get "Expected '.', found '<' [line 1]" error. Not sure if this is the issue with neo4j or mapping file.

Regards
Prashanti
