### ISSUE TITLE
Example code for use as External Library broken

### ISSUE THREAD

**Issue by charlesivie** [RMLio/rmlmapper-java#39]
The example code on the main page about how to use as an external library is broken. The signatures of the methods are out of date, as a consequence, I cannot use the library.

**Comment by pheyvaer** [comment]
Hi @charlesivie 

What exactly are you trying and what are the errors that you are getting?

**Comment by charlesivie** [comment]
Good morning,

The actions I took were the following:

1. Clone your repo 
2. install into my local Maven repository.
3. Create a small project with your example code on how to use it embedded

The result was that the example code on the readme.md was just a little out of date, as many of the method signatures had changed, does this seem right?

I have attempted to spike an example using your tests as a guide, which has proved difficult... Could see the attachment code snippet and see if you can help point me win the right direction? Right now I cannot get it to write to a file, and cannot work out how to choose the output format.   

Thanks in advance for your help!
………

On a more interesting and wider note…

I run a Semantic Web consultancy in London, and we are potentially interested in contributing to the codebase, as it has value for us a library. Ideally I would like to understand the code much better, maybe we can add some comments, more examples etc. 
What do you think? We would need a walk through of the current codebase, as there is quite a lot to digest.

Maybe we could setup a call to discuss?

Thanks,
Regards,
Charles.
Charles Ivie
Director
Email: charles.ivie@semanticintegration.co.uk <mailto:charles.ivie@semanticintegration.co.uk>
Tel: +44 (0)7854 036540 <callto:00447854036540>
Skype: charlieivie <skype:charlieivie>
 <https://www.semanticintegration.co.uk/>
Registered in England and Wales. Company number: 08688966. Registered at:First Floor, Telecom House, 125-135 Preston Road, Brighton, England, BN1 6AF
This email is intended for the addressee named within only. It may contain legally privileged or confidential information. If you are not the named individual you should not read this email and if you do so, you must not under any circumstances make use of the information therein. 
If you have read this email and it is not addressed to you, please notify postmaster@semanticintegration.co.uk <mailto:postmaster@semanticintegration.co.uk> and confirm that it has been deleted from your system and no copies made.

**Comment by charlesivie** [comment]
Hello, 

I managed to get it to write to a file in the end, I had a silly bug in my code! However, the code in the readme.md file still seems out of date. 

Also, I am still very interested in contributing to the codebase, if you would like assistance :)

Many thanks,
Regards,
Charles.
Charles Ivie
Director
Email: charles.ivie@semanticintegration.co.uk <mailto:charles.ivie@semanticintegration.co.uk>
Tel: +44 (0)7854 036540 <callto:00447854036540>
Skype: charlieivie <skype:charlieivie>
 <https://www.semanticintegration.co.uk/>
Registered in England and Wales. Company number: 08688966. Registered at:First Floor, Telecom House, 125-135 Preston Road, Brighton, England, BN1 6AF
This email is intended for the addressee named within only. It may contain legally privileged or confidential information. If you are not the named individual you should not read this email and if you do so, you must not under any circumstances make use of the information therein. 
If you have read this email and it is not addressed to you, please notify postmaster@semanticintegration.co.uk <mailto:postmaster@semanticintegration.co.uk> and confirm that it has been deleted from your system and no copies made.

**Comment by andimou** [comment]
@charlesivie glad that you solved your issue :-) 

We would be up for any collaboration! Feel free to drop us an email at info@rml.io to arrange a call and check how we can proceed!
