### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by amohoste** [RMLio/rmlmapper-java#4]
I was wondering if you have any ETA on the output formats support (turtle, trig) as it would be a very useful feature. At the moment I have the output myself to another data format.

I also saw conditions in the future releases list. Does this mean that conditions don't work with the rmlmapper-java at the moment?

**Comment by bjdmeest** [comment]
We now support other output formats, and join conditions, since 4.1.0. I'm going to close this issue, if you think something is missing, please open a new issue :)
