### ISSUE TITLE
Unable to generate custom mapping

### ISSUE THREAD

**Issue by prashantimaktala** [RMLio/rmlmapper-java#40]
I am trying to convert source xml/json file to RDF using a custom mapping file. 

Source File:
`[
 {
   "ProviderID": 10005,
   "HospitalName": "MARSHALL MEDICAL CENTER SOUTH",
   "Phone Number": 2565938310,
   "Hospital Type": "Acute Care Hospitals",
   "Hospital overall rating": 1,
   "Location": "2505 U S HIGHWAY 431 NORTH BOAZ, AL 35957"
 },
 {
   "ProviderID": 10012,
   "HospitalName": "DEKALB REGIONAL MEDICAL CENTER",
   "Phone Number": 2568453150,
   "Hospital Type": "Acute Care Hospitals",
   "Hospital overall rating": 2,
   "Location": "200 MED CENTER DRIVE FORT PAYNE, AL 35968"
 }
]`

Custom mapping file:

> @prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix xsd: <https://www.w3.org/2001/XMLSchema#>.
@prefix emp: <https://w3id.org/empathi/#>.
@prefix rdfs: <https://www.w3.org/2000/01/rdf-schema#>.
@prefix ex: <http://example.com/ns#>.
ex:HospitalMapping a rr:TriplesMap;
  rml:logicalSource [
    rml:source "listOfHospitals.json" ;
    rml:iterator "/hospital";
    rml:referenceFormulation ql:JSONPath;
  ];
rr:subjectMap [
    rr:template "/ProviderID";
    rr:class emp:Facility
  ];
rr:predicateObjectMap [
    rr:predicate emp:id;
    rr:objectMap [
      rml:reference "/ProviderID";
      rr:datatype xsd:int
    ]
  ];
rr:predicateObjectMap [
    rr:predicate emp:Location;
    rr:objectMap [
      rml:reference "Location"
    ]
  ].

We have run the [RML mapper ](https://github.com/RMLio/rmlmapper-java)which got executed successfully but without any output (no output as result of the conversion). I have used /hospital as the iterator. Is there a way to create a better mapping file for this specific JSON?

**Comment by pheyvaer** [comment]
Hi @prashantimaktala 

There were some issues with the mapping file:
- The Turtle you provided was not valid.
- The iterator did not provide any results.
- The template in the Subject Map did not generate valid IRIs.
- The reference used for the first Object Map did not provide any results.

I created a working mapping file: 

```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix xsd: <https://www.w3.org/2001/XMLSchema#>.
@prefix emp: <https://w3id.org/empathi/#>.
@prefix rdfs: <https://www.w3.org/2000/01/rdf-schema#>.
@prefix ex: <http://example.com/ns#>.

ex:HospitalMapping a rr:TriplesMap;
rml:logicalSource [
rml:source "listOfHospitals.json" ;
rml:iterator "$.[*]";
rml:referenceFormulation ql:JSONPath;
];
rr:subjectMap [
rr:template "http://example.com/{ProviderID}";
rr:class emp:Facility
];
rr:predicateObjectMap [
rr:predicate emp:id;
rr:objectMap [
rml:reference "ProviderID";
rr:datatype xsd:int
]
];
rr:predicateObjectMap [
rr:predicate emp:Location;
rr:objectMap [
rml:reference "Location"
]
].
```
Hope this helps!

**Comment by prashantimaktala** [comment]
Hello Peiter,

Thank you so much. It worked.
I have a question though, what is the purpose of using example.com?

Regards
Prashanti

**Comment by pheyvaer** [comment]
I added `example.com` so that you have valid IRIs, else subjects are not generated. I used `example.com` here, but you can choose your own IRI or use a blank node.

**Comment by prashantimaktala** [comment]
Hi @pheyvaer ,

I'm facing the same issue of no output and no error. Is there a way to figure out what went wrong in such scenario?

Source file:
[
  {
  "id": 77887621,
  "name": "Parkway Campus",
  "amenity_type": "hospital",
  "state_id": "97994878",
  "nodes": "[<overpy.Node id=915490477 lat=34.5765146 lon=-87.0145501>, <overpy.Node id=358983098 lat=34.5768591 lon=-87.0147540>, <overpy.Node id=915490479 lat=34.5780944 lon=-87.0157602>, <overpy.Node id=915490482 lat=34.5770446 lon=-87.0175328>, <overpy.Node id=915490485 lat=34.5755518 lon=-87.0164411>, <overpy.Node id=915490477 lat=34.5765146 lon=-87.0145501>]",
  "location": [
    34.576763183333334,
    -87.01559805
  ],
  "extra_info": {
    "addr:city": "Decatur",
    "addr:housenumber": "1874",
    "addr:postcode": "35603",
    "addr:state": "AL",
    "addr:street": "Beltline Road Southwest",
    "amenity": "hospital",
    "emergency": "yes",
    "gnis:feature_id": "157441",
    "name": "Parkway Campus",
    "opening_hours": "24/7",
    "operator": "Huntsville Hospital Health System",
    "phone": "+1 256 973 6000",
    "website": "http://www.decaturmorganhospital.net/"
   }
 },
 {
  "id": 31440273,
  "name": "Saint Francis Hospital",
  "amenity_type": "hospital",
  "state_id": "97994878",
  "nodes": "[<overpy.Node id=4850203079 lat=32.5068507 lon=-84.9622996>, <overpy.Node id=4850203078 lat=32.5067636 lon=-84.9623598>, <overpy.Node id=4850203077 lat=32.5065896 lon=-84.9623383>, <overpy.Node id=4850203076 lat=32.5060312 lon=-84.9621319>, <overpy.Node id=358701766 lat=32.5056395 lon=-84.9618395>, <overpy.Node id=4850203075 lat=32.5051464 lon=-84.9613623>, <overpy.Node id=4850203074 lat=32.5048563 lon=-84.9610441>, <overpy.Node id=4850203073 lat=32.5046024 lon=-84.9608549>, <overpy.Node id=4850203072 lat=32.5042942 lon=-84.9607990>, <overpy.Node id=4850203071 lat=32.5039352 lon=-84.9607646>, <overpy.Node id=4850203070 lat=32.5038627 lon=-84.9607345>, <overpy.Node id=4850203069 lat=32.5038591 lon=-84.9606399>, <overpy.Node id=4850203068 lat=32.5042543 lon=-84.9596295>, <overpy.Node id=4850203067 lat=32.5047692 lon=-84.9585373>, <overpy.Node id=4850203066 lat=32.5050702 lon=-84.9581761>, <overpy.Node id=4850203065 lat=32.5056105 lon=-84.9576387>, <overpy.Node id=4850203064 lat=32.5059858 lon=-84.9572796>, <overpy.Node id=4850203063 lat=32.5064935 lon=-84.9579783>, <overpy.Node id=4850203062 lat=32.5065497 lon=-84.9579934>, <overpy.Node id=4850203061 lat=32.5067745 lon=-84.9579783>, <overpy.Node id=4850203060 lat=32.5068724 lon=-84.9621878>, <overpy.Node id=4850203079 lat=32.5068507 lon=-84.9622996>]",
  "location": [
    32.50553007727273,
    -84.96031213636364
  ],
  "extra_info": {
    "addr:city": "Columbus",
    "addr:housenumber": "2122",
    "addr:postcode": "31904",
    "addr:street": "Manchester Expressway",
    "amenity": "hospital",
    "emergency": "yes",
    "gnis:feature_id": "322061",
    "name": "Saint Francis Hospital",
    "opening_hours": "24/7",
    "phone": "+1 706 596 4000",
    "website": "https://www.mystfrancis.com/",
    "wikidata": "Q7587967",
    "wikipedia": "en:St. Francis Hospital (Columbus, Georgia)"
  }
 }
]

Mapping file:

@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix xsd: <https://www.w3.org/2001/XMLSchema#>.
@prefix emp: <https://w3id.org/empathi/#>.
@prefix rdfs: <https://www.w3.org/2000/01/rdf-schema#>.
@prefix ex: <http://example.com/ns#>.
@prefix myemp: <https://raw.githubusercontent.com/prashantimaktala/rml-mapping/master/myempathi.owl#>.
@prefix loa: <ttp://www.loa-cnr.it/ontologies/DUL.owl#>.
@prefix eil: <http://ontology.eil.utoronto.ca/icontact.owl#>.


myemp:Hospital a rr:TriplesMap;
rml:logicalSource [
rml:source "OSMhospitals.json" ;
rml:iterator "$";
rml:referenceFormulation ql:JSONPath;
];
rr:subjectMap [
rr:template "https://w3id.org/empathi/Hospital/{HospitalName}";
rr:class myemp:Hospital
];
rr:predicateObjectMap [
rr:predicate myemp:title;
rr:objectMap [
rml:reference "name";
]
];
rr:predicateObjectMap [
rr:predicate myemp:id;
rr:objectMap [
rml:reference "id"
]
];
rr:predicateObjectMap [
rr:predicate myemp:hasLocation;
rr:objectMap [
rml:reference "location"
]
]
.

eil:CellNumber a rr:TriplesMap;
rml:logicalSource [
rml:source "OSMhospitals.json" ;
rml:iterator "$.extra_info[*]";
rml:referenceFormulation ql:JSONPath;
];
rr:subjectMap [
rr:template "http://ontology.eil.utoronto.ca/icontact.owl/{CellNumber}";
rr:class eil:CellNumber
];
rr:predicateObjectMap [
rr:predicate eil:hasPhoneNumber;
rr:objectMap [
rml:reference "phone";
]
]
.
Thanks in advance.

Regards
Prashanti

**Comment by pheyvaer** [comment]
Hi @prashantimaktala 

What output do you get when you provide the option `-v` to the RMLMapper?

**Comment by prashantimaktala** [comment]
Hi @pheyvaer,

-v helped me understand what went wrong. Thank you so much.
