### ISSUE TITLE
A complete example

### ISSUE THREAD

**Issue by hridaydutta123** [RMLio/rmlmapper-java#41]
I tried to use the complete example [here](https://github.com/RMLio/RML-Processor/issues/13). The author mentioned that it is working with the older version of RML-Mapper however after running the same code for the newer version, it is not working. It would be of great help if you can provide a complete example for the latest version. @pheyvaer

**Comment by pheyvaer** [comment]
Hi @hridaydutta123 

The Hydra ontology is not yet supported in the new version. However, the RML rules in that specific example can also be written without Hydra. The mapping file is

```
@prefix rr:     <http://www.w3.org/ns/r2rml#>.
@prefix rml:    <http://semweb.mmlab.be/ns/rml#> .
@prefix crml:   <http://semweb.mmlab.be/ns/crml#> .
@prefix ql:     <http://semweb.mmlab.be/ns/ql#> .
@prefix mail:   <http://example.com/mail#>.
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#>.
@prefix ex:     <http://www.example.com/> .
@base <http://example.com/base> .

<LogicalSource1>
    rml:referenceFormulation ql:JSONPath;
    rml:iterator "$.author[*]".

<#Author>
    rml:logicalSource <LogicalSource1>;

    rr:subjectMap [
        rr:template "http://www.ex.com/author/{ugent_id}";
        rr:class ex:Author
    ];

    rr:predicateObjectMap [
        rr:predicate ex:firstName;

        rr:objectMap [
            rml:reference "first_name" ;
            ]
    ];

    rr:predicateObjectMap [
        rr:predicate ex:lastName;

        rr:objectMap [
            rml:reference "last_name" ;
            ]
    ].
```
and you can the RMLMapper with the following parameters: `-m "mapping.rml.ttl" "<LogicalSource1> rml:source \"https://biblio.ugent.be/publication/{publication_id}.json\"; rml:referenceFormulation ql:CSV ."`, where you change the `publication_id` to the want that is needed.

**Comment by hridaydutta123** [comment]
Thanks @pheyvaer for the prompt response.

**Comment by prashantimaktala** [comment]
Hi Pieter,

I used this example to generate an rdf file. I then loaded RDF file into neo4j to check the nodes and relationships. But it says ""Expected '.', found '<' [line 1]"". Any idea why am I facing this?

Regards
Prashanti

**Comment by pheyvaer** [comment]
Hi @prashantimaktala 

Which RDF file do you mean? The mapping file or the generated output? And could you maybe put this in a separate issue if it is different from this one?
