### ISSUE TITLE
File grel_java_mapping.ttl does not exist

### ISSUE THREAD

**Issue by AlexTo** [RMLio/rmlmapper-java#50]
The class FunctionLoader tries to load the file "grel_java_mapping.ttl" but it doesn't exist in the resource folder so it throws exception.

Could anyone have a look?

Thanks a lot

**Comment by AlexTo** [comment]
Ignore this, I figured out that I need to include this project https://github.com/FnOio/grel-functions-java

**Comment by pheyvaer** [comment]
Hi @AlexTo 

Great you figured it out! If there is anything else, don't hesitate to let us know :smiley:
