### ISSUE TITLE
Question: How to map JSON property to a value instead of a predicate?

### ISSUE THREAD

**Issue by AlexTo** [RMLio/rmlmapper-java#57]
Hi, I have a JSON structure like this
```
{
    "1": {
           "first_name": "Alex",
           "last_name": "To",
           },
     "2": {
           "first_name": "Alex",
           "last_name": "To",
     }
}
```
where "1" and "2" are user ids so I want to map them into triples like these

```
:1    a     :Person .
:2    a     :Person .
```

Of course I can first transform the JSON into some other structure and then do RML mapping but my question is, is there a way to do such mapping without first transforming the JSON?

Thank you

**Comment by DylanVanAssche** [comment]
Currently, the Java implementation of JSONPath doesn't support this option.
There's a [proposal](https://github.com/json-path/JsonPath/issues/439) to add this feature to the implementation.

As a workaround, you can write a custom [FnO](fno.io) to accomplish this.
You can find an example on how to write and implement FnO functions in this
repository: https://github.com/FnOio/grel-functions-java.
