### ISSUE TITLE
Question: How to specify encoding for Input/Output file

### ISSUE THREAD

**Issue by AlexTo** [RMLio/rmlmapper-java#58]
Hi, 

I have an input file with UTF-8 encoding, the literal contains text like this "Hà Nội". But the output file seems to be in ANSI encoding so the text is messed up. Is there a way to specify encoding for input/output file??

Thanks

**Comment by DylanVanAssche** [comment]
Can you provide a minimal reproducible example of some mapping rules, input data and expected output?

You can specify the encoding used by the Java VM with the following options:
- `-Dfile.encoding=UTF-8`
- `-Dfile.encoding=UTF8`

Both should work to specify the file encoding.
