### ISSUE TITLE
Ignore empty cells for rr:IRI

### ISSUE THREAD

**Issue by KMax** [RMLio/rmlmapper-java#59]
I want to convert a CSV file which has empty cells for some of the columns. A part of the mapping:

```
...
rr:objectMap [
  rml:reference "tissue" ;
  rr:termType rr:IRI
]
...
```

I get: 

```
12:57:58.350 [main] ERROR be.ugent.rml.cli.Main               .main(307) - Not a valid (absolute) IRI:
```

because some of the cells in the tissue column are empty.

Can a CLI flag be added which can control whether the emtpy cell are ignored or not? Thank you!

**Comment by DylanVanAssche** [comment]
@KMax Could you provide a minimal failing example?

- Example mapping rules
- Small CSV file for which it fails

**Comment by KMax** [comment]
Just take a CSV file with an empty cell, e.g.:

```
column-a,column-b,column-c
1,,3
```
and map the column-b to an IRI.

**Comment by mathib** [comment]
Hi @KMax ,
I think (can be wrong) you should use the following pattern for the rr:ObjectMap:
```
...
rr:objectMap [
	rr:template "https://mydomain/data#{tissue}" ;
]
...
```
I tested this on an older version of the RML-mapper (v4.6.0) and it does not generate triples with this URI if the `tissue `column is empty.

**Comment by KMax** [comment]
@mathib thanks for sharing! I didn't try your suggestion, but just wanted to share the workaround I applied locally. Output of `git diff`:

```
diff --git a/src/main/java/be/ugent/rml/termgenerator/NamedNodeGenerator.java
b/src/main/java/be/ugent/rml/termgenerator/NamedNodeGenerator.java
index 0c21e86..c18c6a2 100644
--- a/src/main/java/be/ugent/rml/termgenerator/NamedNodeGenerator.java
+++ b/src/main/java/be/ugent/rml/termgenerator/NamedNodeGenerator.java
@@ -24,8 +24,10 @@ public class NamedNodeGenerator extends TermGenerator {
if (objectStrings.size() > 0) {
for (String object : objectStrings) {
-                //todo check valid IRI
-                objects.add(new NamedNode(object));
+                if(object !=null && !object.isEmpty()) {
+                    //todo check valid IRI
+                    objects.add(new NamedNode(object));
+                }
}
}    
```

**Comment by DylanVanAssche** [comment]
You can accomplish this using [FnO](fno.io) functions.
By checking if the string length > 0, you can add a condition to the Triples Map.

The `length` function is described here: https://rml.io/docs/rmlmapper/default-functions/#length
