### ISSUE TITLE
Is there a way to temporarily store a value?

### ISSUE THREAD

**Issue by LasseBeers** [RMLio/rmlmapper-java#60]
Hi, 
I have recently started using RML. I want to map an XML file to OWl and now I have a problem. Maybe someone can help me. I want to address the value of the identifier in the predicateObjectMap. However, the mapping should be universally applicable. Therefore my idea is to write a mapping by addressing the value of the Vmax attribute, caching it and then searching for the value at another place (the ID of the ExternalInterface) to access the value of the identifier attribute.

Is there a way of " storing temporarily" in RML?

           <Attribute Name="VMax" AttributeDataType="xs:IDREF">
              <DefaultValue>100</DefaultValue>
              <Value>af543f28-022c-42cb-a130-e0db2bc64dce</Value>
            </Attribute>

           <ExternalInterface Name="PLC_PRG.Befuellen_Service.Fuellmenge.VMax" ID="af543f28-022c-42cb-a130-e0db2bc64dce" RefBaseClassPath="MTPCommunicationICLib/DataItem/OPCUAItem">
              <Attribute Name="Identifier">
                <Value>|var|WAGO 750-8212 PFC200 G2 2ETH RS.Application.PLC_PRG.Befuellen_Service.Fuellmenge.VMax</Value>
              </Attribute>

I'm new to github and the mapping topic. I hope I was able to describe my problem reasonably well and someone has an idea how I can solve it. 

Thanks a lot in advance

**Comment by thomas-delva** [comment]
Hi Lasse and thank you for trying RML,

What you ask is possible with RML using [join conditions](https://rml.io/specs/rml/#logical-join) between triples maps. Those make it possible to store a value of a "child" reference in one triples map, and generate a triple when a "parent" reference in another triples map has the same value.

In your example that can be used to store the values of the `Value` node when going over `Attribute`s and a triple when this value is the same as the `ID` attribute of an `ExternalInterface`.

This gives the following output, in which a subject created from data of an `Attribute` is linked with an object created from data of an `ExternalInterface`:

```
ex:attributes/VMax ex:predicate ex:externalInterfaces/PLC_PRG.Befuellen_Service.Fuellmenge.VMax .
```

When the following mapping file is used (the reference is defined on lines 15-21):

```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix ex: <http://example.com/> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .

ex:Attributes a rr:TriplesMap;
  rml:logicalSource [ 
    rml:source "input.xml";
    rml:referenceFormulation ql:XPath;
    rml:iterator "//root/Attribute"
  ];
  rr:subjectMap [ rr:template "http://example.com/attributes/{@Name}"; ];
  rr:predicateObjectMap [
    rr:predicate ex:predicate;
    rr:objectMap [
      rr:parentTriplesMap ex:ExternalInterfaces;
      rr:joinCondition [
        rr:child "Value";
        rr:parent "@ID";
      ];
    ];
  ].

ex:ExternalInterfaces a rr:TriplesMap;
  rml:logicalSource [ 
    rml:source "input.xml";
    rml:referenceFormulation ql:XPath;
    rml:iterator "//root/ExternalInterface"
  ];
  rr:subjectMap [ rr:template "http://example.com/externalInterfaces/{@Name}"; ].
```

For the following input file `input.xml` (which is only slightly different from the example you gave):
```
<root>
	<Attribute Name="VMax" AttributeDataType="xs:IDREF">
	    <DefaultValue>100</DefaultValue>
	    <Value>af543f28-022c-42cb-a130-e0db2bc64dce</Value>
	</Attribute>

	<ExternalInterface Name="PLC_PRG.Befuellen_Service.Fuellmenge.VMax" ID="af543f28-022c-42cb-a130-e0db2bc64dce" RefBaseClassPath="MTPCommunicationICLib/DataItem/OPCUAItem">
	    <Attribute Name="Identifier">
		<Value>|var|WAGO 750-8212 PFC200 G2 2ETH RS.Application.PLC_PRG.Befuellen_Service.Fuellmenge.VMax</Value>
	    </Attribute>
	</ExternalInterface>
</root>
```

Let us know if this answers your question,
Kind regards,
Thomas

**Comment by LasseBeers** [comment]
Hi Thomas,
sorry for my late answer. That helps a lot, thanks!
Kind regards,
Lasse
