### ISSUE TITLE
Mapping of special symbols

### ISSUE THREAD

**Issue by LasseBeers** [RMLio/rmlmapper-java#61]
Hi,
The RML mapper sometimes has problems translating special symbols like (). Is there any way to work around the problem?

Example:

Inputline
"MTP_Filter.(0.0.0.0)"

Output
MTP_Filter.%280.0.0.0%29
  
I'd appreciate all the help I can get.

**Comment by thomas-delva** [comment]
Hi Lasse,

The reason the RMLMapper encodes some symbols with a percent sign and two hexadecimal digits, is that those characters are not *URI-safe*.
In the example you give, opening and closing parentheses are encoded as `%28` and `%29` respectively.
You can read more about why certain characters have to be *percent-encoded* before use in URIs in the relevant IETF memo: https://tools.ietf.org/html/rfc3986#section-2.2 .

Kind regards,
Thomas

**Comment by LasseBeers** [comment]
Hi Thomas,
thank you for the answer. Now I understand why they can't be mapped. Then I will simply adjust the output of the mapping manually afterwards. 
Kind regards,
Lasse
