### ISSUE TITLE
nested XPath expressions cannot be processed

### ISSUE THREAD

**Issue by LasseBeers** [RMLio/rmlmapper-java#63]
Hi,

I have a problem with nested Xpath expressing.
A simple nested XPath expression still works, but with much longer processing time from WindowsPowerShell .
Now I tried to map a multiple nested XPath expression. After some hours processing time of WindowsPowerShell I aborted the mapping.
My XPath is:

	rr:template "http://www.hsu-ifa.de/ontologies/MTPOWL#{//ExternalInterface[@ID=//InternalElement/Attribute[Value=//InternalElement[@RefBaseSystemUnitPath='MTPServiceSUCLib/Service'][1]/InternalElement[@RefBaseSystemUnitPath='MTPServiceSUCLib/ServiceParameter/ConfigurationParameter'][1]/Attribute[@Name='RefID']/Value]/parent::InternalElement/Attribute[@Name='VExt']/Value]/Attribute[@Name='Identifier']/Value}";

In the XPath Onlinetester the Xpath expression works perfectly. 
Does anybody know why this could be? Is there a limit in the RML mapper for the XPath expression?

I am grateful for any help. Many thanks in advance.

Kind regards
Lasse

**Comment by DylanVanAssche** [comment]
Hi,

There is no limit in the RMLMapper to the complexity of XPath statements, but maybe the XPath library is used less efficiently than in the online tester. 

What does the mapper write to console when run with the `-v` option?

If possible, you could try to fragment the XML source into smaller files so processing is faster.
