### ISSUE TITLE
Graphs not generated when using functions

### ISSUE THREAD

**Issue by amohoste** [RMLio/rmlmapper-java#7]
I mapped the following yarrrml file to rml: [mapping.yaml.txt](https://github.com/RMLio/rmlmapper-java/files/2273196/mapping.yaml.txt)

This gave me the following rml output: [mapping.rml.txt](https://github.com/RMLio/rmlmapper-java/files/2273203/mapping.rml.txt)

Then I used the following command to map the RML to RDF: `java -jar rmlmapper-0.1.6.jar -m ./mapping.rml -o ./out/out.txt -f ./functions/functions.ttl`

I don't get any graphs in my output however, I just get nTriples while I should get nQuads according to my yarrrml file.

**Comment by pheyvaer** [comment]
Fixed with v0.2.0.
