### ISSUE TITLE
Getting a substring of an attribute from XML base source

### ISSUE THREAD

**Issue by ysghandi** [RMLio/rmlmapper-java#70]
Good day,

I would like to extract part of the XML attribute and assign it to an object type property.
Supposing an input like 
` <Connection Source="HW_sensor.CNF" Destination="HW_pidController.REQ" />`
and the desired substring such as `HW_sensor` happenning before "." 
I tried this code snippet:
`  rr:predicateObjectMap [
    rr:predicate base:isOutputEventOf;
    rr:objectMap [
      rr:template "http://example.com/example#FB-{substring(@Source, lastIndexOf("."))}";
    ];
  ].`
and got error:
`[main] ERROR be.ugent.rml.cli.Main               .main(315) - Expected ']', found '.'`

I would appreciate any help on how to use substring function in RML mapper.

**Comment by bjdmeest** [comment]
@ysghandi , it seems your turtle itself is invalid (you can always check yourself on, e.g. http://ttl.summerofcode.be/),
I think you need to escape the double quotes in the template: `substring(@Source, lastIndexOf(\".\"))`

Does that solve the issue?

**Comment by ysghandi** [comment]
Thank you for your response. No, it doesn't work. 
I tried with `substring-before()` method, which worked.

**Comment by bjdmeest** [comment]
Does that mean this issue can be closed? Can you do that if that's the case? :) If not, could you provide some more information please?

**Comment by ysghandi** [comment]
Yes, I will close it. Thank you!
