### ISSUE TITLE
Found a function using the old `lib:` way, this is deprecated

### ISSUE THREAD

**Issue by CyberDaedalus00** [RMLio/rmlmapper-java#71]
I'm receiving this warning message when I use functions like shown below.  Is there a recommended way to do this?

    rr:subjectMap [
        fnml:functionValue [
            rr:predicateObjectMap [
                rr:predicate fno:executes ;
                rr:objectMap [ rr:constant idlab-fn:random ] 
            ];
            rr:predicateObjectMap [
                rr:predicate grel:array_join ;
                rr:objectMap [ rr:constant "_b:external-reference--"]
            ]
        ] ;
        rr:class stixCore:ExternalReference ;
        rr:termType rr:IRI ;
    ] ;

**Comment by pheyvaer** [comment]
Hi @CyberDaedalus00 

What is the message that you are getting?

**Comment by CyberDaedalus00** [comment]
After fixing the function use as shown below:

rr:subjectMap [
    fnml:functionValue [
        rr:predicateObjectMap [
            rr:predicate fno:executes ;
            rr:objectMap [ rr:constant grel:array_join ] 
        ];
        rr:predicateObjectMap [
            rr:predicate grel:p_array_a ;
            rr:objectMap [ rr:constant "external-reference--" ] # You don't need to include the _b:
        ];
        rr:predicateObjectMap [
            rr:predicate grel:p_array_a ;
            rr:objectMap [
                fnml:functionValue [
                    rr:predicateObjectMap [
                        rr:predicate fno:executes ;
                        rr:objectMap [ rr:constant idlab-fn:random ]  # The random function is nested in the `grel:array_join` function
                    ]
				]
            ]
        ];
    ] ;
    rr:class stixCore:ExternalReference ;
    rr:termType rr:BlankNode; # You do need to set the termType of the subject to BlankNode
] ;
.

I'm still seeing the following lines in the log:

11:15:27.088 [main] WARN  b.ugent.rml.functions.FunctionLoader.getFunction(92) - Found a function using the old `lib:` way, this is deprecated
11:15:27.088 [main] DEBUG be.ugent.rml.functions.FunctionModel.getParameters(133) - No argument was found for following parameter: http://users.ugent.be/~bjdmeest/function/grel.ttl#p_string_sep
11:15:27.089 [main] WARN  b.ugent.rml.functions.FunctionLoader.getFunction(92) - Found a function using the old `lib:` way, this is deprecated
11:15:27.089 [main] DEBUG be.ugent.rml.functions.FunctionModel.getParameters(133) - No argument was found for following parameter: http://users.ugent.be/~bjdmeest/function/grel.ttl#p_string_sep

**Comment by bjdmeest** [comment]
Hi @CyberDaedalus00 ,

You can safely ignore that warning: some parts of the RMLMapper are using an old way of retrieving functions,
which we still need to upgrade at some point.
This is however internal, and has no influence on how to write the RML rules.
So you can ignore it, but I'll keep this issue open to remind us to (i) improve the warning message short term and (ii) upgrade the RMLMapper long term :).

**Comment by DylanVanAssche** [comment]
This issue will be resolved in the next release.

**Comment by DylanVanAssche** [comment]
v6.0.0 switched to Function Agent which addresses this issue.
