### ISSUE TITLE
Condition function (isset, isvalid, equals) example in RML

### ISSUE THREAD

**Issue by ammar257ammar** [RMLio/rmlmapper-java#73]
Dear all,

Can you please guide me to where I can find an example in RML with a condition for generating the triple if the object equals a specific string or isset for example. I can only find an example for YARRRML here (https://rml.io/yarrrml/spec/#conditions) but no example in RML.

Thank you.

Ammar

**Comment by bjdmeest** [comment]
At https://github.com/RMLio/yarrrml-parser/tree/development/test/condition-function-on-po, you can find an example (both in YARRRML as in RML) of using the `idlab-fn:stringContainsOtherString` condition. Replacing with another function should be relatively straightforward, but feel free to get back to us. I'm also keeping this issue open, we could improve on our function documentation :)

**Comment by ammar257ammar** [comment]
Thank you very much. Actually I wanted an example with more readable RML since the generated one from YML is not easy to read and use in a RML mapping.
I managed to write an example for trueCondition function withc "equals" in RML like this:

```{rml}
rr:predicateObjectMap [
	
	rr:predicate npo:NPO_1911 ;
	rr:objectMap [ 
		fnml:functionValue [
			rr:predicateObjectMap [
				rr:predicate fno:executes ;
				rr:objectMap [ rr:constant idlab-fn:trueCondition; rr:termType rr:IRI ]
			];

			rr:predicateObjectMap [
			  rr:predicate idlab-fn:strBoolean ;
			  rr:objectMap <#EqualsFunction>
			];
			
			rr:predicateObjectMap [
			  rr:predicate idlab-fn:str ;
			  rr:objectMap [ rr:constant obo:OBI_0001980 ]
			]
		];
	]
  ].

<#EqualsFunction>
	
	fnml:functionValue [
		rr:predicateObjectMap [
			rr:predicate fno:executes ;
			rr:objectMap [ rr:constant idlab-fn:equal ]
		];

		rr:predicateObjectMap [
		  rr:predicate grel:valueParameter ;
		  rr:objectMap [ rr:constant "MTT" ]
		];
		
		rr:predicateObjectMap [
		  rr:predicate grel:valueParameter2 ;
		  rr:objectMap [ rml:reference "assay" ]
		]
	].
```
