### ISSUE TITLE
Wrong implementation of JsonPath

### ISSUE THREAD

**Issue by Sealdolphin** [RMLio/rmlmapper-java#79]
Hi,

I recently came across a possible bug:

My JSON architecture looks like this:
```
{
  "elementStore": [
    {
      "type" : "type1",
      "elements": [
        {
          "ord": "first"
        },
	{
          "ord": "second"
        },
        {
          "ord": "third"
        }
      ]
    },
{
      "type": "type2",
      "elements": [
        {
          "ord": "first2"
        },
	{
          "ord": "second2"
        },
        {
          "ord": "third2"
        }
      ]
    }
}
```
And I tried to extract the different element ordinals (_ord_) with the help of JSONPath. My RML fragment:
```
<#elementsMap> a rr:TriplesMap;

	rml:logicalSource [ 
		rml:source "<my JSON file>";
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$.elementStore[*]";
	];

	rr:subjectMap [ 
		rr:template "/{.elements[*].ord}";
		rr:class mm:ordinal;
	];

```

I expected that the result should include all three elements however, I only got the first one

**Comment by pheyvaer** [comment]
Hi @Sealdolphin 

Can you explain what the expected result is in terms of RDF?

**Comment by Sealdolphin** [comment]
Hi, yes, although I think I found the problem in the [source code.](https://github.com/RMLio/rmlmapper-java/blob/ca29c8e18717b802e32b62bb17ec3725b5bba344/src/main/java/be/ugent/rml/records/JSONRecord.java#L55)

**Comment by Sealdolphin** [comment]
@pheyvaer is it intended behavior, or should it return all possible JSONPath records as subjects?

**Comment by pheyvaer** [comment]
I would expect the RML to be something like this to get the RDF you want

```
<#elementsMap> a rr:TriplesMap;

	rml:logicalSource [ 
		rml:source "<my JSON file>";
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$.elementStore[*].elements[*]";
	];

	rr:subjectMap [ 
		rr:template "{ord}";
		rr:class mm:ordinal;
	];
```

And this because your subjects are in the `elements` array and not in the `elementStore` array. Well at least not directly.

**Comment by Sealdolphin** [comment]
> I would expect the RML to be something like this to get the RDF you want

Thanks for the fast response. This mapping does work indeed, however this way I cannot access any other property of the objects in the elementStore (besides elements). Is there a way to make _my_ mapping work, or do I want to use the RML inherently the wrong way?

**Comment by pheyvaer** [comment]
Hi @Sealdolphin 

Yeah, the problem is that JSONPath is limited in that regard and at the moment there is not other reference formulation available for JSON and thus also not implemented in the RMLMapper. Preprocessing the JSON structure to work around this issue is the best option at the moment. We have done this too before in the past.
