### ISSUE TITLE
Tests stuck on database startup complete

### ISSUE THREAD

**Issue by amohoste** [RMLio/rmlmapper-java#8]
When trying to compile version `0.2.0`of the rmlmapper, the test keeps hanging on `[main] INFO ch.vorburger.mariadb4j.DB - Database startup complete.` not allowing me to build the rmlmapper into a jar. I skipped these tests for now but I guess this isn't really the intention.

**Comment by pheyvaer** [comment]
You have to set the correct flag of local tests. See the end of the README.
