### ISSUE TITLE
XPath Node Name Mapping

### ISSUE THREAD

**Issue by PK2511** [RMLio/rmlmapper-java#83]
Hello,

I am trying to map predicates from node names in XML files.

#### Example of XML
```
 <ns1:lecture1 name = "Math"> ..... </ns1:lecture1>
 <ns2:lecture2 name = "English"> ..... </ns2:lecture2>
 <ns3:lecture3 name = "German"> ..... </ns3:lecture3>
```
#### Expected RDF
```
ex:uni  ns1:lecture1 [ ex:name "Math" ;
                                  rdf:value "..." . ] ;
           ns2:lecture2 [ ex:name "English" ;
                                  rdf:value "..." . ] ;
           ns3:lecture3 [ ex:name "German" ;
                                  rdf:value "..." . ] .
```

-------------------------------------------------------------------------------------
Please could you suggest what should I put in the predicate mapping. The node names are diversified.
So I would like to find a dynamic mapping approach.
Thank you so much :)

```
 rr:subjectMap [
    rr:constant  ex:uni;
  ]; 
  
    rr:predicateObjectMap [ 
      rr:predicate   ??; 

    rr:objectMap ......
    ....
    .....
```

**Comment by bjdmeest** [comment]
Dear PK2511,

I think this is more of an XPath issue than an RML one. If the root node would be `<x>`, you could select all values that have attribute `name` with something like `//x/*[@name]` in your iterator
