### ISSUE TITLE
test.sh fails and mvn clean install too

### ISSUE THREAD

**Issue by paulakeen** [RMLio/rmlmapper-java#88]
I cloned the rmlapper repository and run first the test.sh script and then the mvn clean install command and both failed. The exception goes like this. I have a question: Why you cannot distribute the jar file? 

Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Mapper_MappingFile_URL_Test.testInvalidMappingURL »  Unexpected exception, exp...
[ERROR]   Mapper_MySQL_Test.before:27->MySQLTestCore.setUpMySQLDBInstance:33 » ManagedProcess
[ERROR]   Mapper_OracleDB_Test.doMapping:104->mappingTest:120 » SQL No suitable driver f...
[INFO] 
[ERROR] Tests run: 343, Failures: 0, Errors: 3, Skipped: 7
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 min
[INFO] Finished at: 2020-12-01T04:20:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project rmlmapper: There are test failures.
[ERROR] 
[ERROR] Please refer to /Volumes/ext-hd/RML-Mapper/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by pheyvaer** [comment]
Hi @paulakeen 

Best is to execute `test.sh -n`. That way Oracle tests are not executed. We are not allowed to add the Oracle driver in our jar, because that is not allowed by the license of the driver.

**Comment by paulakeen** [comment]
with 'tst.sh' -n still fails, I'm afraid. This time it's MySQL: 

[INFO] 
[ERROR] Errors: 
[ERROR]   Arguments_Test_MySQL.before:24->MySQLTestCore.setUpMySQLDBInstance:33 » ManagedProcess
[ERROR]   Mapper_MySQL_Test.before:27->MySQLTestCore.setUpMySQLDBInstance:33 » ManagedProcess
[INFO] 
[ERROR] Tests run: 343, Failures: 0, Errors: 2, Skipped: 7
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2020-12-01T10:21:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project rmlmapper: There are test failures.
[ERROR]

**Comment by paulakeen** [comment]
I just realised you have the jars in the release branches!

**Comment by pheyvaer** [comment]
Normally there are more detailed errors, besides the error at the end. There it should explain what the cause of the failure is.
