### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by vemonet** [RMLio/rmlmapper-java#9]
`mvn clean install` fails due to tests errors:
```shell
  Mapper_RDBs_Test.evaluate_XXXX_RDBs_PostgreSQL:652 » PSQL The connection attem...
  Mapper_RDBs_Test.evaluate_XXXX_RDBs_SQLServer:829->executeSQL:967 » SQLServer ...
  Mapper_RDBs_Test.evaluate_0002i_RDBs_SQLServer »  Unexpected exception, expect...

Tests run: 222, Failures: 0, Errors: 72, Skipped: 7
```

Here is my `maven -version`:

```shell
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-34-generic", arch: "amd64", family: "unix"
```

Do you plan to use Docker to make it run? To make sure it is running in the same environment for everyone using it

**Comment by pheyvaer** [comment]
Did you set boolean to true for local testing as mentioned [here](https://github.com/RMLio/rmlmapper-java/blob/master/README.md#rdbs)?

Eventually, we will add a Docker image yes.

**Comment by vemonet** [comment]
Additional informations: this file can be found at the following location: `src/test/java/be/ugent/rml/Mapper_RDBs_Test.java`
https://github.com/RMLio/rmlmapper-java/blob/master/src/test/java/be/ugent/rml/Mapper_RDBs_Test.java#L37

I changed it and still get the same.

Docker running with following version:
`Docker version 18.06.1-ce, build e68fc7a`

I will try it out anyway, I built the jar using `-DskipTests`

**Comment by bjdmeest** [comment]
@vemonet our latest release (https://github.com/RMLio/rmlmapper-java/releases/tag/v4.3.2) should fix this, please let us know if there are still any issues :)
