### ISSUE TITLE
Specify input path to CSV

### ISSUE THREAD

**Issue by ahmad88me** [RMLio/rmlmapper-java#90]
Hi, I was wondering if there is a way to specify the path of the CSV as an input to the JAR.
Thanks,

**Comment by pheyvaer** [comment]
So you mean do dynamically update the RML file?

**Comment by ahmad88me** [comment]
@pheyvaer I mean to pass the parent path.
For example: `java -jar mapper.jar --parentpath /opt/data`. 
and the location of the RML is: `/opt/data/myrml.ttl`

**Comment by pheyvaer** [comment]
And how does that relate to the CSV file?

**Comment by ahmad88me** [comment]
@pheyvaer ops! I mean the location of the CSV file.
So for example if the CSV file is located in `/opt/data/mydata.csv` and the mapping file  `mydata.csv` as the rml:source. 
From my understanding, I have to be in `/opt/data` to generate the data in RDF, right?

My question is that if there is a way to specify the home or parent path of the CSV file, something like this:
```java -jar mapper.jar --inputparentpath /opt/data -m /opt/data/myrml.ttl```

**Comment by pheyvaer** [comment]
You have the option to use the full path in `rml:source` so instead of saying `rml:source "mydata.csv"`, you can have `rml:source "/opt/data/mydata.csv"`. In the latter case you don't have to be in the folder `/opt/data`.

**Comment by ahmad88me** [comment]
@pheyvaer Thanks for the clarification
